usd-cs/COMP-49X-24-25-our-search

- .github/workflows/super-linter.yml
- backend/build.gradle.kts
- backend/src/main/java/COMP_49X_our_search/backend/database/entities/Department.java
- backend/src/main/java/COMP_49X_our_search/backend/database/entities/Faculty.java
- backend/src/main/java/COMP_49X_our_search/backend/database/entities/Major.java
- backend/src/main/java/COMP_49X_our_search/backend/database/entities/Project.java
- backend/src/main/java/COMP_49X_our_search/backend/database/entities/ResearchPeriod.java
- backend/src/main/java/COMP_49X_our_search/backend/database/entities/Student.java
- backend/src/main/java/COMP_49X_our_search/backend/database/entities/UmbrellaTopic.java
- backend/src/main/java/COMP_49X_our_search/backend/database/repositories/DepartmentRepository.java
- backend/src/main/java/COMP_49X_our_search/backend/database/repositories/FacultyRepository.java
- backend/src/main/java/COMP_49X_our_search/backend/database/repositories/MajorRepository.java
- backend/src/main/java/COMP_49X_our_search/backend/database/repositories/ProjectRepository.java
- backend/src/main/java/COMP_49X_our_search/backend/database/repositories/ResearchPeriodRepository.java
- backend/src/main/java/COMP_49X_our_search/backend/database/repositories/StudentRepository.java
- backend/src/main/java/COMP_49X_our_search/backend/database/repositories/UmbrellaTopicRepository.java
- backend/src/main/java/COMP_49X_our_search/backend/database/services/DepartmentService.java
- backend/src/main/java/COMP_49X_our_search/backend/database/services/MajorService.java
- backend/src/main/java/COMP_49X_our_search/backend/database/services/ProjectService.java
- backend/src/main/resources/application.properties
- backend/src/test/java/COMP_49X_our_search/backend/database/DepartmentServiceTest.java
- backend/src/test/java/COMP_49X_our_search/backend/database/MajorServiceTest.java
- backend/src/test/java/COMP_49X_our_search/backend/database/ProjectServiceTest.java
Created table entities for:
- Department
- Faculty
- Major
- Project
- ResearchPeriod
- Student
- UmbrellaTopic
- Relationships between tables
> Initial database setup with Spring JPA

- .gitignore
- frontend/package-lock.json
- frontend/package.json
- frontend/src/__tests__/TitleButton.test.js
- frontend/src/components/TitleButton.js
- frontend/src/resources/constants.js
made tests and a title button that will go in the upper left corner 
when clicked it will reload the page
also updated gitignore
and created a constants.js file where we can store constant strings instead of hardcoding them
> Title button

- frontend/.gitignore
- frontend/package-lock.json
- frontend/package.json
- frontend/src/__tests__/PostDialog.test.js
- frontend/src/components/PostDialog.js
This request implements a frontend feature known as PostDialog and fixes some structuring within the file structure.
Post UI: Implemented a PostDialog component that shows up as a popup for displaying detailed information about research opportunities, including project name, description, qualifications, topics, research periods, status, and faculty details.
Gitignore Update: Added .vscode/ to .gitignore 
Project Structure: Created components and __tests__ folders for better organization of components and unit tests.
Testing: Wrote and verified unit tests for PostDialog.
> Frontend UI implementation (PostDialog)

- frontend/src/__tests__/PostList.test.js
- frontend/src/components/PostDialog.js
- frontend/src/components/PostList.js
- frontend/src/resources/mockData.js
we learned that each project will only have one faculty so only the one will be displayed
> Changed faculty object from array to json

- README.md
- backend/Dockerfile
- compose.yml
- frontend/Dockerfile
- frontend/src/resources/constants.js
- frontend/src/utils/fetchPostings.js
- made dockerfiles
- compose.yml
- everything works
- comments explaining files
- edit constants.js on the frontend and fetchPostings to display correct when backend returns empty list or responds with not 200
> Docker setup

- .github/workflows/pull_request_template.md
Setting up a pull request template to improve our pull request descriptions.
> Add Standard COMP492 PR Template

- backend/src/main/java/COMP_49X_our_search/backend/database/entities/Discipline.java
- backend/src/main/java/COMP_49X_our_search/backend/database/entities/Major.java
- backend/src/main/java/COMP_49X_our_search/backend/database/entities/Project.java
- backend/src/main/java/COMP_49X_our_search/backend/database/entities/Student.java
- backend/src/main/java/COMP_49X_our_search/backend/database/repositories/DisciplineRepository.java
- backend/src/main/java/COMP_49X_our_search/backend/database/repositories/MajorRepository.java
- backend/src/main/java/COMP_49X_our_search/backend/database/repositories/ProjectRepository.java
- backend/src/main/java/COMP_49X_our_search/backend/database/services/DisciplineService.java
- backend/src/main/java/COMP_49X_our_search/backend/database/services/MajorService.java
- backend/src/main/java/COMP_49X_our_search/backend/fetcher/DisciplineFetcher.java
- backend/src/main/java/COMP_49X_our_search/backend/fetcher/FetcherModuleController.java
- backend/src/main/java/COMP_49X_our_search/backend/fetcher/ProjectFetcher.java
- backend/src/main/java/COMP_49X_our_search/backend/gateway/GatewayController.java
- backend/src/main/java/COMP_49X_our_search/backend/gateway/dto/DisciplineDTO.java
- backend/src/main/java/COMP_49X_our_search/backend/gateway/dto/ProjectHierarchyDTO.java
- backend/src/main/java/COMP_49X_our_search/backend/gateway/util/ProjectHierarchyConverter.java
- backend/src/main/java/COMP_49X_our_search/backend/util/ProtoConverter.java
- backend/src/main/proto/data/entities.proto
- backend/src/main/proto/fetcher/data_types.proto
- backend/src/main/proto/fetcher/fetcher_module.proto
- backend/src/main/resources/application.properties
- backend/src/test/java/COMP_49X_our_search/backend/database/DisciplineServiceTest.java
- backend/src/test/java/COMP_49X_our_search/backend/database/MajorServiceTest.java
- backend/src/test/java/COMP_49X_our_search/backend/database/ProjectServiceTest.java
- backend/src/test/java/COMP_49X_our_search/backend/fetcher/DisciplineFetcherTest.java
- backend/src/test/java/COMP_49X_our_search/backend/fetcher/FetcherModuleControllerTest.java
- backend/src/test/java/COMP_49X_our_search/backend/fetcher/ProjectFetcherTest.java
- backend/src/test/java/COMP_49X_our_search/backend/gateway/GatewayControllerTest.java
- backend/src/test/java/COMP_49X_our_search/backend/gateway/ModuleInvokerTest.java
- backend/src/test/java/COMP_49X_our_search/backend/gateway/ProjectHierarchyConverterTest.java
Changed from x_departments to x_disciplines as per Dr. Clark's feedback, except for faculty_departments. Added student-research field interest relationship.
> Added disciplines JPA Entity. Changed x_departments relationships

- frontend/src/components/MainAccordion.js
- frontend/src/components/MainLayout.js
- frontend/src/components/MajorAccordion.js
- frontend/src/components/PostDialog.js
- frontend/src/components/PostList.js
- frontend/src/components/SearchBar.js
- frontend/src/components/Sidebar.js
- frontend/src/components/TitleButton.js
- frontend/src/components/ViewProfile.js
Added header comments using JSDoc for better documentation.
> Added header comments

- .github/workflows/super-linter.yml
**Summary:** Changed VALIDATE_ALL_CODEBASE linter config to false so that it only checks for new code, as we've already validated the entire codebase prior to this PR.
> Changed VALIDATE_ALL_CODEBASE linter config to false

- backend/.gitignore
- frontend/src/App.js
- frontend/src/__tests__/App.test.js
- frontend/src/resources/constants.js
**Summary:**
Created a function on the frontend that makes a request to the backend for the user's authentication status.
None
The frontend app now checks the user's authentication status by making a request to the backend. Then it renders the main layout only if the backend says they are authenticated.
1. go to http:localhost:3000
2. see that the app no longer renders the main layout because you have not logged in yet. For now, it renders text that says that the landing page will be present.
> Frontend check auth cal

- backend/src/main/java/COMP_49X_our_search/backend/database/services/UserService.java
- backend/src/test/java/COMP_49X_our_search/backend/database/UserServiceTest.java
New Feature
**Summary:**
Added method in `UserService` to check if a user with a given email exists in the database.
1) Make sure that there is at least 1 valid user in the database.
2) Create a helper class that calls the `userExists()` method from the `UserService` passing either a valid email or an invalid one, and verify the boolean result.
> Added method to check if a user already exists in the database

- frontend/src/__tests__/PostDialog.test.js
- frontend/src/components/PostDialog.js
- frontend/src/resources/mockData.js
Implemented change of view for student and faculty for the pop up. Based on the user's role (student or faculty), the dialog displays different information.
The layout remains similar, but the content in column 3 now differs based on the user type.
Use student view and faculty view in order to verify the dialog.
> Implemented change of view for student and faculty for the pop up

- frontend/src/__tests__/MainLayout.test.js
- frontend/src/__tests__/PostDialog.test.js
- frontend/src/components/MainLayout.js
- frontend/src/components/PostDialog.js
- frontend/src/resources/mockData.js
- frontend/src/utils/fetchPostings.js
**Type of Change:**  Bug Fix
**Summary:** 
Fixed bugs in post dialog component on the frontend. It was having runtime errors because there were some logical errors and the data was not being passed down correctly. Now the user can see the correct information when they click on the posts. 
No changes
None
None
None
1. hardcode isAuthenticated to true in App.js
2. make sure there is data in your sql db
3. hardcode isStudent to true -> you will be able to click on the posts and the popup will appear
4. or hardcode isFaculty to true -> ^
> Render students postdialog integration and fixes

- backend/src/main/java/COMP_49X_our_search/backend/database/entities/Student.java
- backend/src/main/java/COMP_49X_our_search/backend/database/repositories/StudentRepository.java
- backend/src/main/java/COMP_49X_our_search/backend/database/services/StudentService.java
- backend/src/main/java/COMP_49X_our_search/backend/fetcher/FetcherModuleController.java
- backend/src/main/java/COMP_49X_our_search/backend/fetcher/ProjectFetcher.java
- backend/src/main/java/COMP_49X_our_search/backend/fetcher/StudentFetcher.java
- backend/src/main/java/COMP_49X_our_search/backend/gateway/GatewayController.java
- backend/src/main/java/COMP_49X_our_search/backend/gateway/dto/MajorDTO.java
- backend/src/main/java/COMP_49X_our_search/backend/gateway/dto/StudentDTO.java
- backend/src/main/java/COMP_49X_our_search/backend/gateway/util/ProjectHierarchyConverter.java
- backend/src/main/java/COMP_49X_our_search/backend/util/ProtoConverter.java
- backend/src/main/proto/data/entities.proto
- backend/src/main/proto/fetcher/data_types.proto
- backend/src/main/proto/fetcher/fetcher_module.proto
- backend/src/test/java/COMP_49X_our_search/backend/fetcher/FetcherModuleControllerTest.java
- backend/src/test/java/COMP_49X_our_search/backend/fetcher/ProjectFetcherTest.java
- backend/src/test/java/COMP_49X_our_search/backend/fetcher/StudentFetcherTest.java
- backend/src/test/java/COMP_49X_our_search/backend/gateway/GatewayControllerTest.java
- backend/src/test/java/COMP_49X_our_search/backend/gateway/ProjectHierarchyConverterTest.java
**Summary:**
- Added new fetcher type `StudentFetcher` that returns all students organized by major and discipline.
- Added endpoint "/students" that returns the data.
- Added new `StudentFetcher` in the `Fetcher` module that calls the database to retrieve all students and groups them by major and research field interest, and discipline.
- Updated `FetcherModuleController` to support `StudentFetcher`
- Refactored Fetcher type handling in `FetcherModuleController` to use Maps instead of if statements.
- Added `StudentService` with methods `getStudentsByMajorId` and `getStudentsByResearchFieldInterestId`.
1. Make sure that the database has …
> Created endpoint to retrieve students

- frontend/src/__tests__/StudentProfileForm.test.js
- frontend/src/components/FacultyProfileForm.js
- frontend/src/components/StudentProfileForm.js
**Type of Change:** **New Feature**
**Summary:** Fixes issues with the multi-select functionality in the Student Profile Form view and form submission tests
Navigate to the Student Profile form in the application.
Verify that "Create Your Student Profile" is present.
In the Research Field multi-select dropdown, select multiple options (e.g., "Artificial Intelligence" and "Cybersecurity") and confirm that multiple selections appear.
Fill in the remaining form fields and submit the form.
> Student multi select

- frontend/src/__tests__/FacultyProfileForm.test.js
- frontend/src/__tests__/StudentProfileForm.test.js
- frontend/src/components/FacultyProfileForm.js
- frontend/src/components/StudentProfileForm.js
**Type of Change:** _TODO:_ Pick one of the following: **Refactoring**
**Summary:** This pull request updates the student and faculty profile forms. In the StudentProfileForm, the email field has been removed and replaced with a Graduation Year field. Additionally, the "Research Field" label is updated to "Research Field Interest(s)"  and both the Major and Research Period dropdowns have been converted to multi-select. For the FacultyProfileForm, the email field has been removed.
Student Profile Form:
Removed the email field.
Added a new Graduation Year field.
Renamed the "Research Field" dropdown to "Research Field Interest(s)" and added helper text: "Select all Research Fields that you're interested in. Include major if desired."
Converted the Major and Research Period dropdowns to …
> Profile form fixes

- frontend/src/__tests__/FacultyProfileForm.test.js
- frontend/src/__tests__/StudentProfileForm.test.js
- frontend/src/components/FacultyProfileForm.js
- frontend/src/components/StudentProfileForm.js
**Type of Change:**  Other
**Summary:** 
Added transitions for create profile forms. Now successfully creating a profile sends the user to /posts. Error message renders on screen if something fails. Enforces user to input first and last name. Made some UI tweaks to make it more user friendly. Edge case error handling if the backend needs the user to re-login again.
Changed some wording from major to major(s) and research period to research period interest(s). Rearranged so that class status and graduation year follow each other and then major and research field interests follow each other. It flows better. Displays error messages to user.
None
None
None
1. login
2. choose a role
3. check out the profile forms
4. try to submit without the backend running and error messages will display
> Create profile success routes and error handling

- backend/src/main/java/COMP_49X_our_search/backend/gateway/GatewayController.java
- backend/src/main/java/COMP_49X_our_search/backend/gateway/dto/CreateStudentRequestDTO.java
- backend/src/test/java/COMP_49X_our_search/backend/gateway/GatewayControllerTest.java
**Type of Change:** Bug fix
**Summary:**
Changed expected type of graduationYear from int to String in create student profile request to align with the frontend requests.
Changed type of `graduationYear` in `CreateStudentRequestDTO` from `int` to `String`
N/A
> Changed expected type of graduationYear from int to String

- backend/src/main/java/COMP_49X_our_search/backend/database/repositories/DepartmentRepository.java
- backend/src/main/java/COMP_49X_our_search/backend/database/repositories/FacultyRepository.java
- backend/src/main/java/COMP_49X_our_search/backend/database/services/DepartmentService.java
- backend/src/main/java/COMP_49X_our_search/backend/database/services/FacultyService.java
- backend/src/main/java/COMP_49X_our_search/backend/gateway/GatewayController.java
- backend/src/main/java/COMP_49X_our_search/backend/gateway/dto/CreateFacultyRequestDTO.java
- backend/src/main/java/COMP_49X_our_search/backend/profile/FacultyProfileCreator.java
- backend/src/main/java/COMP_49X_our_search/backend/profile/ProfileModuleController.java
- backend/src/main/java/COMP_49X_our_search/backend/security/SecurityConfig.java
- backend/src/main/proto/data/entities.proto
- backend/src/main/proto/profile/profile_module.proto
- backend/src/test/java/COMP_49X_our_search/backend/gateway/GatewayControllerTest.java
- backend/src/test/java/COMP_49X_our_search/backend/profile/FacultyProfileCreatorTest.java
- backend/src/test/java/COMP_49X_our_search/backend/profile/ProfileModuleControllerTest.java
**Summary:** Added endpoint `/api/facultyProfiles` to allow faculty profile and user creation.
- Added `FacultyProfileCreator` class that implements the `ProfileCreator` interface and is responsible for creating faculty profiles, which involves inputing the data into a new entry in the `faculty` and `users` tables.
- Added `FacultyService` with methods `existsByEmail()` and `saveFaculty()`.
- Added extra query methods in the hibernate entity services to support the needed operations.
1. Make sure the frontend app, backend app, and the mysql database are running.
2. Send `/api/facultyProfiles` request from the frontend to the backend
3. …
> Implemented create faculty endpoint

- backend/src/test/java/COMP_49X_our_search/backend/database/DepartmentServiceTest.java
- backend/src/test/java/COMP_49X_our_search/backend/database/DisciplineServiceTest.java
- backend/src/test/java/COMP_49X_our_search/backend/database/MajorServiceTest.java
- backend/src/test/java/COMP_49X_our_search/backend/database/ProjectServiceTest.java
- backend/src/test/java/COMP_49X_our_search/backend/database/ResearchPeriodServiceTest.java
- backend/src/test/java/COMP_49X_our_search/backend/util/ProtoConverterTest.java
**Type of Change:** Chore
**Summary:** Updated tests for better test coverage.
N/A
> Updated tests for better coverage

- backend/src/main/java/COMP_49X_our_search/backend/profile/StudentProfileCreator.java
**Type of Change:** Bug fix
**Summary:** Fixed error where isActive is retrieved from proto structure but it should always be true when creating a new profile.
N/A
> Fixed error where isActive is retrieved from proto structure

- backend/src/main/java/COMP_49X_our_search/backend/security/OAuthSuccessHandler.java
- frontend/src/__tests__/FacultyProfileForm.test.js
- frontend/src/__tests__/MajorAccordion.test.js
- frontend/src/__tests__/StudentProfileForm.test.js
- frontend/src/components/FacultyProfileForm.js
- frontend/src/components/MajorAccordion.js
- frontend/src/components/StudentProfileForm.js
**Summary:** Added a log in the backend with system.out.println for debugging purposes; changed some UI on the frontend
no
no
no
no
1. login
2. backend logs will say your email
3. creating a profile will have real values for dropdownlists
> Wording tweaks

- backend/src/main/java/COMP_49X_our_search/backend/gateway/GatewayController.java
**Type of Change:** Bug fix
**Summary:** Field `hasPriorExperience` is now being set when creating a student.
N/A
> Added missing hasPriorExperience field when creating a student

- backend/src/main/java/COMP_49X_our_search/backend/database/repositories/StudentRepository.java
- backend/src/main/java/COMP_49X_our_search/backend/database/services/StudentService.java
- backend/src/main/java/COMP_49X_our_search/backend/gateway/GatewayController.java
- backend/src/main/java/COMP_49X_our_search/backend/gateway/util/ProjectHierarchyConverter.java
- backend/src/main/java/COMP_49X_our_search/backend/profile/ProfileModuleController.java
- backend/src/main/java/COMP_49X_our_search/backend/profile/ProfileRetriever.java
- backend/src/main/java/COMP_49X_our_search/backend/profile/StudentProfileRetriever.java
- backend/src/main/proto/profile/profile_module.proto
- backend/src/test/java/COMP_49X_our_search/backend/database/StudentServiceTest.java
- backend/src/test/java/COMP_49X_our_search/backend/gateway/GatewayControllerTest.java
- backend/src/test/java/COMP_49X_our_search/backend/profile/ProfileModuleControllerTest.java
- backend/src/test/java/COMP_49X_our_search/backend/profile/StudentProfileRetrieverTest.java
**Summary:** Created endpoint to retrieve the currently logged in student's profile.
- Added `ProfileRetriever` interface in the `Profile` module with `retrieveProfile()` method, as a new type of operation that the module supports.
- Added `StudentProfileRetriever` class that implements the `ProfileRetriever` interface and is responsible for retrieving a student profile by email.
- Added extra query methods in the hibernate entity service to support the needed operations.
- Created endpoint method that receives `/api/studentProfiles/current` requests from the frontend and calls the `ProfileRetriever` module using the currently logged in …
> Implemented retrieve student profile endpoint

- backend/src/main/java/COMP_49X_our_search/backend/database/entities/Department.java
- backend/src/main/java/COMP_49X_our_search/backend/database/entities/Major.java
- backend/src/main/java/COMP_49X_our_search/backend/database/entities/ResearchPeriod.java
- backend/src/main/java/COMP_49X_our_search/backend/database/services/DepartmentService.java
- backend/src/main/java/COMP_49X_our_search/backend/database/services/MajorService.java
- backend/src/main/java/COMP_49X_our_search/backend/database/services/ResearchPeriodService.java
- backend/src/main/java/COMP_49X_our_search/backend/gateway/GatewayController.java
- backend/src/main/java/COMP_49X_our_search/backend/gateway/dto/DepartmentDTO.java
- backend/src/main/java/COMP_49X_our_search/backend/gateway/dto/MajorDTO.java
- backend/src/main/java/COMP_49X_our_search/backend/gateway/dto/ResearchPeriodDTO.java
- backend/src/test/java/COMP_49X_our_search/backend/database/DepartmentServiceIntegrationTest.java
- backend/src/test/java/COMP_49X_our_search/backend/database/DepartmentServiceTest.java
- backend/src/test/java/COMP_49X_our_search/backend/database/MajorServiceIntegrationTest.java
- backend/src/test/java/COMP_49X_our_search/backend/database/MajorServiceTest.java
- backend/src/test/java/COMP_49X_our_search/backend/database/ResearchPeriodServiceTest.java
- backend/src/test/java/COMP_49X_our_search/backend/gateway/GatewayControllerTest.java
- backend/src/test/resources/application-test.properties
- compose.yaml
- frontend/src/App.js
- frontend/src/__tests__/FacultyProfileForm.test.js
- frontend/src/__tests__/StudentProfileForm.test.js
- frontend/src/components/Auth/RequireAuthAndNoProfile.js
- frontend/src/components/FacultyProfileForm.js
- frontend/src/components/StudentProfileForm.js
- frontend/src/utils/fetchDepartments.js
- frontend/src/utils/fetchMajors.js
- frontend/src/utils/fetchResearchPeriods.js
**Summary:** Created backend endpoints to return data about the departments, majors, and research periods from the database. Updated the frontend so the data returned by the backend populates the frontend form controls when creating a profile. Now there is no hard coded data, preventing 400 responses from the database if the frontend hardcoded values don't match the backend/databases values. This required me to add fetch calls and loading states to the profile form components. All backend and frontend tests updated accordingly. Also added two integration tests for department service and major service.
No changes
No changes
No changes
These services now return lists of the records (encapsulated by DTOs) in the database:
- DepartmentService
- MajorService
- …
> Populate dropdowns dynamically

- frontend/src/__tests__/StudentProfileView.test.js
- frontend/src/components/StudentProfileView.js
**Type of Change:** **New Feature**
**Summary:**
A new StudentProfileView component is made. This includes fetching to the database to retrieve profile into to pass to view. Also, this pull request includes button on the bottom to edit profile.
No changes made to the UI/UX beyond those implemented in the StudentProfileView component. The component maintains consistency with our Material-UI design.
Launch the application and navigate to the StudentProfileView component.
When a successful fetch occurs, check that all profile fields (name, graduation year, major, class status, research field interests, research periods, interest reason, and prior research experience) are …
> Student Profile View

- frontend/src/__tests__/StudentProfileEdit.test.js
- frontend/src/components/StudentProfileEdit.js
…nt test file.
**Type of Change:**  **New Feature**
**Summary:** : 
Fetches the current student's profile data and pre-fills the form so you can update it right away. The form now uses multi-select dropdowns for class status, major, and research field interests, a radio button group for prior research experience, and includes a checkbox to mark the profile as inactive. On submission, it sends the updated info to the backend and shows error or success messages based on the response.
The edit profile form is designed using Material-UI for a clean layout. It pre-populates all fields with the current student data so users can easily update their information. Multi-select dropdowns are used for class status, major, and research field interests, ensuring users can select multiple options.
This …
> Edit Student Profile

- frontend/src/__tests__/ViewProfile.test.js
- frontend/src/components/ViewProfile.js
**Summary:** Dropdown menu for the students and faculty on their profile
Designed UI element to show a dropdown when the student or faculty clicks on their profile, giving them the option to logout, create a new project.
No changes made. 
Create a profile and click on the top-right corner in order to see the implemented UI.
> Implemented view profile dropdown for students and faculty

- frontend/src/__tests__/FacultyProfileView.test.js
- frontend/src/components/FacultyProfileView.js
**Type of Change:**  **New Feature**
**Summary:** 
FacultyProfileView fetches the current faculty profile data from the backend and displays it, including the faculty's name, email, and department. 
It shows a loading spinner while fetching data, displays an error message if something goes wrong, and shows profile information in a Paper component with labeled fields. The Back button navigates to the posts page, and the Edit Profile button is at the bottom.
Open the FacultyProfileView page.
Confirm that a loading spinner appears initially.
Verify that the faculty's name, email, and department are displayed correctly.
Check that the Back and Edit Profile buttons are visible …
> Faculty Profile View

- backend/src/main/java/COMP_49X_our_search/backend/database/entities/Discipline.java
- backend/src/main/java/COMP_49X_our_search/backend/database/services/DisciplineService.java
- backend/src/main/java/COMP_49X_our_search/backend/gateway/GatewayController.java
- backend/src/main/java/COMP_49X_our_search/backend/gateway/dto/DisciplineDTO.java
- backend/src/test/java/COMP_49X_our_search/backend/database/DisciplineServiceTest.java
- backend/src/test/java/COMP_49X_our_search/backend/gateway/GatewayControllerTest.java
**Type of Change:**New Feature,
**Summary:** Created backend endpoint to return list of disciplines from the database
No changes
Discipline entity overloading constructors for testing purposes
No changes
DisciplineService method to get all disciplines returns them in sorted order ascending
1. login
2. go to backendurl/disciplines and you will get a list of the disciplines in the db
> Get disciplines

- backend/src/main/java/COMP_49X_our_search/backend/gateway/GatewayController.java
- backend/src/test/java/COMP_49X_our_search/backend/gateway/GatewayControllerTest.java
- frontend/src/__tests__/StudentProfileEdit.test.js
- frontend/src/components/StudentProfileEdit.js
**Type of Change:** Bug Fix.
**Summary:** Changed endpoint for editing students in the frontend from `/api/studentProfiles` to `/api/studentProfiles/current`. Changed endpoint in the backend from `POST` to `PUT` and from `/api/studentProfiles/edit` to `/api/studentProfiles/current`
N/A
> Fixed endpoints for editing students

- frontend/src/App.js
- frontend/src/__tests__/ResearchOpportunityForm.test.js
- frontend/src/components/ResearchOpportunityForm.js
- frontend/src/utils/fetchDisciplines.js
- frontend/src/utils/fetchUmbrellaTopics.js
**Summary:** Faculty research opportunity form. It allows faculty to choose their preferences from the research wanted.
-Active/inactive status
-Dropdowns for research fields
-Semester period selection
-Form validation with error messages
Login as faculty and go to create research opportunity.
> Implemented Research Opportunities Form

- backend/src/main/java/COMP_49X_our_search/backend/BackendApplication.java
- backend/src/main/java/COMP_49X_our_search/backend/database/entities/User.java
- backend/src/main/java/COMP_49X_our_search/backend/database/repositories/UserRepository.java
- backend/src/main/java/COMP_49X_our_search/backend/database/services/UserService.java
- backend/src/main/java/COMP_49X_our_search/backend/util/UserExpirationChecker.java
- backend/src/main/resources/application.properties
- backend/src/test/java/COMP_49X_our_search/backend/database/UserServiceTest.java
- backend/src/test/java/COMP_49X_our_search/backend/util/UserExpirationCheckerTest.java
**Summary:** Added class that checks when every user was created and if older than 4 years it gets deleted.
Updated user entity to include a createdAt field.
A new service class, UserExpirationChecker, has been added. This class uses Spring's @Scheduled annotation to periodically check all users. if user is older than 4 years it gets deleted.
- Ensure that the property user.expiration.years is set to 4 in your application.properties
- Create user profiles with varying createdAt dates (e.g. 3 and 5 years)
- Start the application 1 minute before midnight (or change the cron expression in UserExpirationChecker class)
- Verify that the old user is deleted
> Finished implementing class to delete users after 4 years

- frontend/src/App.js
- frontend/src/__tests__/profiles/FacultyProfileEdit.test.js
- frontend/src/components/ResearchOpportunityForm.js
- frontend/src/components/profiles/FacultyProfileEdit.js
- frontend/src/components/profiles/StudentProfileEdit.js
- frontend/src/resources/mockData.js
**Type of Change:** Bug fixes
**Summary:** 
- fixed faculty edit bug so now the current options are preselected and removable. 
- Fixed logout so it correctly logs user out. 
- fixed student profile edit so it sends correct request body to backend.
- Wrote comments for how things are rendered on the frontend to avoid confusion in the future.
None
None
None
None
1. login as faculty
2. go to edit profile. you can unselect and select different departments
> Faculty edit and logout bugs

- backend/src/main/java/COMP_49X_our_search/backend/database/repositories/UmbrellaTopicRepository.java
- backend/src/main/java/COMP_49X_our_search/backend/database/services/ProjectService.java
- backend/src/main/java/COMP_49X_our_search/backend/database/services/UmbrellaTopicService.java
- backend/src/main/java/COMP_49X_our_search/backend/gateway/GatewayController.java
- backend/src/main/java/COMP_49X_our_search/backend/gateway/ModuleInvoker.java
- backend/src/main/java/COMP_49X_our_search/backend/gateway/dto/CreateProjectRequestDTO.java
- backend/src/main/java/COMP_49X_our_search/backend/gateway/dto/CreateProjectResponseDTO.java
- backend/src/main/java/COMP_49X_our_search/backend/gateway/dto/CreatedProjectDTO.java
- backend/src/main/java/COMP_49X_our_search/backend/gateway/dto/EditStudentRequestDTO.java
- backend/src/main/java/COMP_49X_our_search/backend/profile/ProfileModuleController.java
- backend/src/main/java/COMP_49X_our_search/backend/project/ProjectCreator.java
- backend/src/main/java/COMP_49X_our_search/backend/project/ProjectModuleController.java
- backend/src/main/proto/core/core.proto
- backend/src/main/proto/project/project_module.proto
- backend/src/test/java/COMP_49X_our_search/backend/database/ProjectServiceTest.java
- backend/src/test/java/COMP_49X_our_search/backend/database/UmbrellaTopicServiceTest.java
- backend/src/test/java/COMP_49X_our_search/backend/gateway/GatewayControllerTest.java
- backend/src/test/java/COMP_49X_our_search/backend/gateway/ModuleInvokerTest.java
- backend/src/test/java/COMP_49X_our_search/backend/project/ProjectModuleControllerTest.java
- frontend/src/__tests__/profiles/StudentProfileEdit.test.js
- frontend/src/__tests__/profiles/StudentProfileView.test.js
- frontend/src/components/profiles/StudentProfileEdit.js
- frontend/src/components/profiles/StudentProfileView.js
- frontend/src/resources/mockData.js
**Type of Change:** New Feature & Bug Fixes
**Summary:** Added `POST` `/create-project` endpoint to create a project / research opportunity. Fixed response format response misalignments in the frontend and backend.
- Added `Project` module that will be responsible for executing project operations, e.g. create, edit, delete. Currently, it only supports project creation, but in the future it will also support the previously mentioned operations.
- Added `ProjectCreator` class that is responsible for creating projects under a faculty member, which involves inputting the data into a new entry in the `projects` database and its respective relationships.
- Added extra query …
> Implement create project endpoint & bug fixes

- backend/docs/architecture_full.puml
- backend/docs/architecture_simplified.puml
**Type of Change:** Documentation
**Summary:** Added two PUML diagrams of the backend architecture, one being a simplified version.
N/A
N/A
N/A
N/A
> Added PUML class diagrams for the backend architecture

- backend/src/main/java/COMP_49X_our_search/backend/database/repositories/StudentRepository.java
- backend/src/main/java/COMP_49X_our_search/backend/database/services/StudentService.java
- backend/src/main/java/COMP_49X_our_search/backend/gateway/GatewayController.java
- backend/src/test/java/COMP_49X_our_search/backend/database/StudentServiceTest.java
- backend/src/test/java/COMP_49X_our_search/backend/gateway/GatewayControllerTest.java
**Summary:** Added a new API endpoint to delete a student by ID. This endpoint communicates with the profile module to remove the student's profile and returns HTTP status codes based on the operation's success.
Login in as an admin, access the student page, select student and click "delete" button.
> Implemented endpoint to delete a specific student

- backend/src/main/java/COMP_49X_our_search/backend/gateway/GatewayController.java
- backend/src/main/java/COMP_49X_our_search/backend/gateway/dto/DeleteStudentRequestDTO.java
- backend/src/test/java/COMP_49X_our_search/backend/gateway/GatewayControllerTest.java
**Summary:** Fixed endpoint format for deleting a specific student. I overlooked the required format when reviewing the PR.
- Added `DeleteStudentRequestDTO` class.
N/A
> Fixed endpoint format for delete student

- backend/src/main/java/COMP_49X_our_search/backend/gateway/GatewayController.java
- backend/src/main/java/COMP_49X_our_search/backend/gateway/dto/EditStudentRequestDTO.java
- backend/src/test/java/COMP_49X_our_search/backend/gateway/GatewayControllerTest.java
**Summary:** Implemented editStudent endpoint in GatewayController to verify proper processing of student profile edits.
>Be a student
>Edit your profile as a student.
> Implemented editStudent

- backend/src/main/java/COMP_49X_our_search/backend/database/services/ProjectService.java
- backend/src/main/java/COMP_49X_our_search/backend/gateway/GatewayController.java
- backend/src/main/java/COMP_49X_our_search/backend/gateway/dto/CreateProjectRequestDTO.java
- backend/src/main/java/COMP_49X_our_search/backend/project/ProjectEditor.java
- backend/src/main/java/COMP_49X_our_search/backend/project/ProjectModuleController.java
- backend/src/main/proto/project/project_module.proto
- backend/src/test/java/COMP_49X_our_search/backend/gateway/GatewayControllerTest.java
- backend/src/test/java/COMP_49X_our_search/backend/project/ProjectCreatorTest.java
- backend/src/test/java/COMP_49X_our_search/backend/project/ProjectEditorTest.java
- backend/src/test/java/COMP_49X_our_search/backend/project/ProjectModuleControllerTest.java
**Summary:** Added `PUT` mapping at `/project` endpoint to edit a specific project by its id.
- Added `ProjectEditor` class in `Project` module that will be responsible for editing a specific project by its id.
- Added extra query methods in the jpa entity service to support the needed operaitons.
1. Make sure the frontend app, backend app, and the mysql database are running and that there is valid project data in the database.
2. Send `PUT` request to endpoint `localhost:8080/project` including the id in the request body and verify that the response is as expected, and that the project was successfully edited.
> Implemented edit project endpoint

- backend/src/main/java/COMP_49X_our_search/backend/database/repositories/StudentRepository.java
- backend/src/main/java/COMP_49X_our_search/backend/database/services/FacultyService.java
- backend/src/main/java/COMP_49X_our_search/backend/database/services/StudentService.java
- backend/src/main/java/COMP_49X_our_search/backend/database/services/UmbrellaTopicService.java
- backend/src/main/java/COMP_49X_our_search/backend/gateway/GatewayController.java
- backend/src/test/java/COMP_49X_our_search/backend/database/StudentServiceTest.java
- backend/src/test/java/COMP_49X_our_search/backend/gateway/GatewayControllerTest.java
**Summary:** Faculty deletion endpoint to request correctly the the faculty's email and ensure deletion.
>Be admin
>Delete faculty
> Implemented deleteFacultyEndpoint

- frontend/src/components/ResearchOpportunityForm.js
- frontend/src/components/projects/ProjectEdit.js
**Summary:** Made a few small changes to the frontend forms that let users create and edit projects. Now umbrella topics and research periods are not required to submit.
1. login as faculty or admin
2. go to create or edit project
3. submit without umbrella topics or research periods selected works
> frontend - creating and editting project does not require umbrella topics or research periods

- backend/.dockerignore
- compose.yaml
- frontend/.dockerignore
- frontend/Dockerfile
- nginx.conf
**Summary:** Created dockerignore files and edited the frontend's Dockerfile to try to optimize docker compose. It was taking a long time to run. Hoping this can make things faster.
1. Run docker compose up --build. Hoping it takes less than 5 minutes to get app up on local machine.
> dockerignore files to try to optimize build

- backend/src/main/java/COMP_49X_our_search/backend/gateway/GatewayController.java
- backend/src/main/java/COMP_49X_our_search/backend/gateway/dto/CreateMajorRequestDTO.java
- backend/src/test/java/COMP_49X_our_search/backend/gateway/GatewayControllerTest.java
**Summary:** Added `POST` mapping at `/major` endpoint to create a new major.
- Added `CreateMajorRequestDTO` class for parsing frontend request format.
1. Make sure the frontend app, the backend app, and the mysql database are running.
2. Send `POST` request to endpoint `https://localhost:8080/major` including the needed data in the request body and verify that the response is as expected, and that the major was successfully created.
> Implemented create new major endpoint

- backend/src/main/java/COMP_49X_our_search/backend/gateway/GatewayController.java
- backend/src/test/java/COMP_49X_our_search/backend/gateway/GatewayControllerTest.java
**Summary:** Added `GET` mapping at `/project` endpoint to get a specific project by its id.
1. Make sure the frontend app, the backend app, and the mysql database are running.
2. Send `GET` request to endpoint `https://localhost:8080/major` including the project id in the URL params and verify that the response is as expected.
> Implemented get specific project endpoint

- backend/src/main/java/COMP_49X_our_search/backend/gateway/GatewayController.java
- backend/src/test/java/COMP_49X_our_search/backend/gateway/GatewayControllerTest.java
**Type of Change:** _TODO:_ Pick one of the following: New Feature, Bug Fix, Documentation, Refactoring, or Other.
**Summary:** _TODO: Briefly summarize the changes made in this pull request, including the rationale for the changes._
_TODO: Describe what changes were made to the UI/UX for this request. This could include things such as new workflows added (e.g. logging in) and redesigns of existing UI elements.
Provide either a link to your Figma or directly embed an image showing the relevant screens.
If no changes were made, simply state, "No changes made."_
_TODO: Describe what changes were made to your data model for this request. This could include things such as new database tables added and …
> Created endpoint and test to get specific faculty.

- backend/src/main/java/COMP_49X_our_search/backend/gateway/GatewayController.java
- backend/src/test/java/COMP_49X_our_search/backend/gateway/GatewayControllerTest.java
**Type of Change:** _TODO:_ Pick one of the following: New Feature, Bug Fix, Documentation, Refactoring, or Other.
**Summary:** _TODO: Briefly summarize the changes made in this pull request, including the rationale for the changes._
_TODO: Describe what changes were made to the UI/UX for this request. This could include things such as new workflows added (e.g. logging in) and redesigns of existing UI elements.
Provide either a link to your Figma or directly embed an image showing the relevant screens.
If no changes were made, simply state, "No changes made."_
_TODO: Describe what changes were made to your data model for this request. This could include things such as new database tables added and …
> Created endpoint and relevant test for getting the specific student.

- backend/src/main/java/COMP_49X_our_search/backend/gateway/util/ProjectHierarchyConverter.java
- backend/src/main/java/COMP_49X_our_search/backend/util/ProtoConverter.java
- backend/src/main/proto/data/entities.proto
- backend/src/test/java/COMP_49X_our_search/backend/fetcher/StudentFetcherTest.java
- backend/src/test/java/COMP_49X_our_search/backend/profile/StudentProfileRetrieverTest.java
- backend/src/test/java/COMP_49X_our_search/backend/util/ProtoConverterTest.java
**Type of Change:** Refactoring
**Summary:** Refactored code so id's are properly included in responses.
N/A
> Refactored code to properly include ids

- backend/src/main/java/COMP_49X_our_search/backend/database/services/ResearchPeriodService.java
- backend/src/main/java/COMP_49X_our_search/backend/gateway/GatewayController.java
- backend/src/test/java/COMP_49X_our_search/backend/database/ResearchPeriodServiceTest.java
- backend/src/test/java/COMP_49X_our_search/backend/gateway/GatewayControllerTest.java
**Summary:** Added `DELETE` mapping at `/research-period` endpoint to delete a specific research period by its id.
- Added additional method in the jpa ResearchPeriodService class to support the needed operations.
N/A
> Finished implementation

- backend/src/main/java/COMP_49X_our_search/backend/gateway/GatewayController.java
- backend/src/test/java/COMP_49X_our_search/backend/gateway/GatewayControllerTest.java
**Type of Change:** _TODO:_ Pick one of the following: New Feature, Bug Fix, Documentation, Refactoring, or Other.
**Summary:** _TODO: Briefly summarize the changes made in this pull request, including the rationale for the changes._
_TODO: Describe what changes were made to the UI/UX for this request. This could include things such as new workflows added (e.g. logging in) and redesigns of existing UI elements.
Provide either a link to your Figma or directly embed an image showing the relevant screens.
If no changes were made, simply state, "No changes made."_
_TODO: Describe what changes were made to your data model for this request. This could include things such as new database tables added and …
> Edit specific department

- backend/src/main/java/COMP_49X_our_search/backend/database/entities/EmailNotification.java
- backend/src/main/java/COMP_49X_our_search/backend/database/enums/EmailNotificationType.java
- backend/src/main/java/COMP_49X_our_search/backend/database/repositories/EmailNotificationRepository.java
- backend/src/main/java/COMP_49X_our_search/backend/database/services/EmailNotificationService.java
- backend/src/main/java/COMP_49X_our_search/backend/gateway/GatewayController.java
- backend/src/main/java/COMP_49X_our_search/backend/gateway/dto/EmailNotificationDTO.java
- backend/src/test/java/COMP_49X_our_search/backend/database/EmailNotificationServiceTest.java
- backend/src/test/java/COMP_49X_our_search/backend/gateway/GatewayControllerTest.java
**Summary:** Added a PUT endpoint at /email-notifications to update email notification templates by type, with validation ensuring that type, subject, and body are not empty.
Integrated new update logic into EmailNotificationService and GatewayController.
Send a PUT request to /email-notifications with a JSON array containing valid email templates and verify the updates; invalid input should return a 400 status.
> implemented editEmailNotificationTest

- compose.yaml
- frontend/src/__tests__/admin/add/handleAddDepartment.test.js
- frontend/src/__tests__/admin/add/handleAddDiscipline.test.js
- frontend/src/__tests__/admin/add/handleAddMajor.test.js
- frontend/src/__tests__/admin/add/handleAddPeriod.test.js
- frontend/src/__tests__/admin/add/handleAddUmbrella.test.js
- frontend/src/components/posts/PostDialog.js
- frontend/src/utils/adminFetching.js
**Summary:** Fixed bug on frontend: handle delete was not passing id to request
> Bug fix: deleting on frontend request

- backend/src/main/java/COMP_49X_our_search/backend/database/services/UmbrellaTopicService.java
- backend/src/main/java/COMP_49X_our_search/backend/gateway/GatewayController.java
- backend/src/test/java/COMP_49X_our_search/backend/database/UmbrellaTopicServiceTest.java
**Type of Change:** Bug fix.
**Summary:** Fixed logic to account for project relationship when deleting umbrella topic
N/A
> Add project check to umbrella topic deletion

- frontend/public/index.html
**Type of Change:** Chore
**Summary:** Changed the website description so when the link is sent for the website it says what the OUR SEARCH program is in a short sentence. Before, it said the default "website created using create-react-app" but that is not professional or meaningful to anyone. 
1. (after the frontend image is updated) copy the link https://oursearch.dedyn.io and paste it in slack
2. website description will say what the OUR SEARCH is
> updated index.html description 

- compose.yaml
- frontend/src/App.js
- frontend/src/__tests__/PersistentAlert.test.js
- frontend/src/__tests__/admin/add/handleAddDepartment.test.js
- frontend/src/__tests__/admin/add/handleAddDiscipline.test.js
- frontend/src/__tests__/admin/add/handleAddMajor.test.js
- frontend/src/__tests__/admin/add/handleAddPeriod.test.js
- frontend/src/__tests__/admin/add/handleAddUmbrella.test.js
- frontend/src/__tests__/admin/delete/handleDeleteDiscipline.test.js
- frontend/src/__tests__/admin/view/ManageVariables.test.js
- frontend/src/components/FAQs.js
- frontend/src/components/PersistentAlert.js
- frontend/src/components/admin/ManageVariables.js
- frontend/src/resources/constants.js
- frontend/src/utils/adminFetching.js
- frontend/src/utils/fetchDisciplines.js
- frontend/src/utils/getDataFrom.js
**Type of Change:** Refactoring
**Summary:** Refactored `ManageAppVariables.js` and `FAQs.js` and `adminFetching.js` so that:
1. they don't show loading screens if the db doesn't data in it. This way admins can add data for the first time.
2. the error messages are persistent on the top of the page. For this I created a component called `PersistentAlert.js` that we can use whenever we want to show alerts that stay on the page "floating". This way you can see the alert no matter where you are on the page. 
3. they use a common `getDataFrom(url)` function instead of separate `fetchDisicplines()`, `fetchResearchPeriods()`, etc functions. For better code reusability/avoiding repetitive code. The separate functions were all redundant except for the urls. Will have to implement this refactoring …
> Refactor: admin manage vars and FAQs

- backend/src/main/java/COMP_49X_our_search/backend/database/services/FaqService.java
- backend/src/test/java/COMP_49X_our_search/backend/database/FaqServiceTest.java
**Summary:** Fixed bug where passing condition for deleting an faq was if the faq does not exist, when it should be does exist instead
No chanes made.
N/A
> Fixed conditional when deleting Faq

- backend/src/test/java/COMP_49X_our_search/backend/database/FaqServiceIntegrationTest.java
**Summary:** Added Faq service integration test
N/A
> Added faq service integration test

- compose.yaml
- frontend/cypress/e2e/landingPageTest.cy.js
- frontend/package-lock.json
- frontend/package.json
New Feature
**Summary:** 
Introduces a new E2E test for the Landing Page component for the application.
No changes made. 
Open the Cypress UI in the terminal with "npx cypress open"
Run landingPageTest.cy.js in the UI and ensure test passes.
> Created an E2E test for the landing page.

- frontend/src/__tests__/profiles/FacultyProfileView.test.js
- frontend/src/__tests__/profiles/StudentProfileView.test.js
- frontend/src/components/profiles/FacultyProfileView.js
- frontend/src/components/profiles/StudentProfileView.js
**Type of Change:** Refactoring
**Summary:** Changed design for the student and faculty view.
Improved design for the student and profile view. It now shows more icons and looks more aesthetic.
>Make a profile (student or faculty)
>Go to the profile edit on the top right button. 
>Click on the profile and edit.
> Refactored faculty and student profile view

- frontend/src/__tests__/popups/AreYouSureDialog.test.js
- frontend/src/components/popups/AreYouSureDialog.js
**Other** (improving older feature)
**Summary:** 
This feature Uses a different MUI library to style the dialog container (with rounded corners and deeper shadow). Also, adds a warning icon in the header. Also, highlights the "Delete" word in the confirmation message. Now displays the error message in red which makes the button more whole.
Navigate to any of the five pages that call the AreYouSure dialog component. 
Press the "Delete" button on any of the five pages (FAQs.js, ManageVariables.js, PostDialog.js, FacultyProfileView.js, and StudentProfileView.js)
Confirm that the Are You Sure dialog has the new features.
> Enhancing "Are You Sure" Dialog

- frontend/src/__tests__/filtering/SearchBar.test.js
- frontend/src/__tests__/filtering/Sidebar.test.js
- frontend/src/__tests__/posts/PostsLayout.test.js
- frontend/src/components/filtering/SearchBar.js
- frontend/src/components/filtering/Sidebar.js
- frontend/src/components/posts/PostsLayout.js
- frontend/src/resources/constants.js
**Summary:** 
- search bar is now on the side bar
- Side bar filters show up for projects: majors, research periods, umbrella topics
- side bar filters show up for students: majors, research periods
https://www.figma.com/design/Ve26dsULmd1hGR3WQMilFL/sprint-6?node-id=0-1&p=f&t=NYuoUq80GryEbiFC-0
none
none
none
1. login as admin or faculty
2. see filters for students and all projects
3. click apply to trigger fetch to backend with filters in URL params
4. click reset to remove filters from being checked
> feature: frontend displays filters

- frontend/src/__tests__/profiles/FacultyProfileEdit.test.js
- frontend/src/__tests__/profiles/StudentProfileEdit.test.js
- frontend/src/components/popups/ClickForInfo.js
- frontend/src/components/profiles/FacultyProfileEdit.js
- frontend/src/components/profiles/StudentProfileEdit.js
**Type of Change:** Refactoring Design
**Summary:** Improved design for StudentProfileEdit ad FacultyProfileEdit
-Added more color and icons for a more friendly user approach.
-The layout is bigger.
-Changed small details on the boxes. 
-Go to the profile (Top right corner)
-Go to edit projects(if faculty) or edit profile(if student)
> Improve student faculty edit

- backend/src/main/java/COMP_49X_our_search/backend/fetcher/FacultyFetcher.java
- backend/src/main/java/COMP_49X_our_search/backend/fetcher/ProjectFetcher.java
- backend/src/main/java/COMP_49X_our_search/backend/fetcher/StudentFetcher.java
- backend/src/main/java/COMP_49X_our_search/backend/gateway/GatewayController.java
- backend/src/main/java/COMP_49X_our_search/backend/profile/FacultyProfileRetriever.java
- backend/src/main/proto/fetcher/fetcher_module.proto
- backend/src/main/proto/profile/profile_module.proto
- backend/src/test/java/COMP_49X_our_search/backend/fetcher/FacultyFetcherTest.java
- backend/src/test/java/COMP_49X_our_search/backend/fetcher/ProjectFetcherTest.java
- backend/src/test/java/COMP_49X_our_search/backend/fetcher/StudentFetcherTest.java
- backend/src/test/java/COMP_49X_our_search/backend/gateway/GatewayControllerTest.java
- backend/src/test/java/COMP_49X_our_search/backend/profile/FacultyProfileRetrieverTest.java
**Summary:** Implemented filtering logic for students, projects, and faculty. The filtering logic will be as follows:
- Within a specific category, filters use `OR` logic, e.g. if we select Computer Science and Biology, it should show results that are in either of those majors.
- Across categories, filters use `AND` logic, e.g. if we select Computer Science for the major and Fall 2025 for the research period, it will show results that meet both of these conditions. Note that it retains the logic within categories, e.g. if we select Computer Science and Biology for the majors and Fall 2025 for the research period, the results should meet the following condition `(Computer Science OR Biology) AND (Fall 2025)`
- Keywords will be used for searching through the …
> Implemented filter logic

- backend/src/main/java/COMP_49X_our_search/backend/fetcher/StudentFetcher.java
**Summary:** Fixed bug where filtering students by keywords was not case insensitive.
N/A
> Fixed filter being case sensitive bug

- frontend/cypress/e2e/create-project-button.cy.js
- frontend/cypress/e2e/filter-projects.cy.js
- frontend/cypress/e2e/search-bar.cy.js
- frontend/cypress/e2e/switch-views.cy.js
- frontend/cypress/support/commands.js
- frontend/cypress/support/e2e.js
- frontend/src/App.js
**Testing/New Feature**
**Summary:** 
Bypassed Authentication in App.js: Modified App.js to detect if Cypress is running (window.Cypress) and immediately authenticates the user. This allowed access to /posts without needing any OAuth login.
Four E2E tests were created:
search-bar.cy.js: Verifies that the search bar works and is functional on the /posts page.
filter-projects.cy.js: Opens the filter sidebar, expands available filter categories (Majors, Research Periods, Umbrella Topics), and clicks "Apply."
switch-views.cy.js: Simulates a faculty user switching between Students, All Projects, and My Projects views.
create-project-button.cy.js: Verifies that the "Create Project" button navigates properly to the Create Project form page.
This section …
> More E2E Tests

- frontend/src/__tests__/posts/MainAccordion.test.js
- frontend/src/components/posts/MainAccordion.js
- frontend/src/components/posts/PostsLayout.js
**Summary:** Fixed the frontend so now when user is admin and they can see the total results/number of faculty showing up and the total number of faculty per department. I forgot to implement this earlier.
No change
No change
No change
No change
2. click faculty to see faculty posts
3. verify totals are correct
> Bug fix: showing total number of faculty 

- backend/src/main/java/COMP_49X_our_search/backend/database/enums/EmailNotificationType.java
- backend/src/main/java/COMP_49X_our_search/backend/database/services/EmailNotificationService.java
- backend/src/main/resources/email-notifications.json
- backend/src/test/java/COMP_49X_our_search/backend/database/EmailNotificationServiceTest.java
**Summary:** Added functionality to auto-populate email notification templates into the database on startup.
- Updated `EmailNotificationService` to include a `@PostConstruct` method that loads email templates from a new config file `email-notifications.json` and saves the templates into the database if they're missing, i.e. if the database already contains the entries, it won't do anything.
1. Make sure that the `email-notifications.json` is present and has valid data.
2. Start the app
3. Check the `email_notifications` table to make sure that the data was populated. Additionally, data can be removed from the table to verify that it's …
> Implemented email notification template auto-populating

- backend/src/main/java/COMP_49X_our_search/backend/gateway/GatewayController.java
- backend/src/main/java/COMP_49X_our_search/backend/gateway/dto/AdminEmailDTO.java
**New Feature**
**Summary:** 
Added endpoints for getting, deleting, and adding the admin email. 
2. go to manage app variables
3. try to add and delete admin emails
> Making Admin Email Endpoints

- backend/src/main/java/COMP_49X_our_search/backend/database/entities/WeeklyNotificationSchedule.java
- backend/src/main/java/COMP_49X_our_search/backend/database/entities/YearlyNotificationSchedule.java
- backend/src/main/java/COMP_49X_our_search/backend/database/repositories/WeeklyNotificationScheduleRepository.java
- backend/src/main/java/COMP_49X_our_search/backend/database/repositories/YearlyNotificationScheduleRepository.java
- backend/src/main/java/COMP_49X_our_search/backend/database/services/WeeklyNotificationScheduleService.java
- backend/src/main/java/COMP_49X_our_search/backend/database/services/YearlyNotificationScheduleService.java
- backend/src/main/java/COMP_49X_our_search/backend/notifications/EmailNotificationScheduler.java
- backend/src/main/resources/email-notification-schedule-defaults.json
**Summary:** Implemented auto-population for email notification timestamps with default values if they don't exist in the database. Added boilerplate code for the scheduler service that will send notifications periodically.
- Added new table `weekly_notification_schedule` with fields `id` and `notificationDay` (Mon-Sun). Weekly notifications will be sent every week on the specified day.
- Added new table `yearly_notification_schedule` with fields `id` and `notificationDateTime`. Yearly notifications will be sent every year on the specified date.
- Added corresponding services for the new tables added
- Added `EmailNotificationScheduler` class with …
> Implemented email notification timestamp auto-population

- frontend/src/components/admin/AdminEmailNotification.js
- frontend/src/components/admin/WeeklyNotificationSelector.js
**New Feature**
**Summary:** 
The WeeklyNotificationDaySelector component that lets the admin pick which day of the week their “weekly” emails should go out. 
Navigate to the Admin Email Notification page
Ensure that the component is visible.
> Admin weekly update

- frontend/src/components/posts/PostList.js
**Summary:** Implemented the email hyperlink
Added email icon functionality to the existing PostList component. When clicked, the icon opens the USD Gmail compose window with pre-populated recipient, subject, and a template message
Enhanced the PostList component with a handleEmailClick function that processes email addresses from post.faculty.email (for faculty) and post.email (for students). 
-Log in as a student and view research opportunities
-Faculty email address in the "To" field
-Research opportunity name in the subject line
-Template greeting in the email body
-Test the same workflow as faculty viewing student profiles
-Confirm that admin views …
> Email Implementation

- backend/build.gradle.kts
- backend/src/main/java/COMP_49X_our_search/backend/database/entities/Project.java
- backend/src/main/java/COMP_49X_our_search/backend/database/entities/ProjectStudentMatches.java
- backend/src/main/java/COMP_49X_our_search/backend/database/entities/StudentFacultyMatches.java
- backend/src/main/java/COMP_49X_our_search/backend/database/repositories/EmailNotificationRepository.java
- backend/src/main/java/COMP_49X_our_search/backend/database/repositories/ProjectRepository.java
- backend/src/main/java/COMP_49X_our_search/backend/database/repositories/ProjectStudentMatchesRepository.java
- backend/src/main/java/COMP_49X_our_search/backend/database/repositories/StudentFacultyMatchesRepository.java
- backend/src/main/java/COMP_49X_our_search/backend/database/repositories/UserRepository.java
- backend/src/main/java/COMP_49X_our_search/backend/database/services/EmailNotificationService.java
- backend/src/main/java/COMP_49X_our_search/backend/database/services/FacultyService.java
- backend/src/main/java/COMP_49X_our_search/backend/database/services/ProjectService.java
- backend/src/main/java/COMP_49X_our_search/backend/database/services/ProjectStudentMatchesService.java
- backend/src/main/java/COMP_49X_our_search/backend/database/services/StudentFacultyMatchesService.java
- backend/src/main/java/COMP_49X_our_search/backend/database/services/StudentService.java
- backend/src/main/java/COMP_49X_our_search/backend/database/services/UserService.java
- backend/src/main/java/COMP_49X_our_search/backend/notifications/EmailNotificationScheduler.java
- backend/src/main/java/COMP_49X_our_search/backend/notifications/MatchBuilder.java
- backend/src/main/java/COMP_49X_our_search/backend/notifications/SendGridService.java
- backend/src/main/resources/application.properties
- backend/src/test/java/COMP_49X_our_search/backend/database/ProjectServiceTest.java
- backend/src/test/java/COMP_49X_our_search/backend/database/StudentServiceTest.java
- backend/src/test/resources/application-test.properties
- start.sh
**Summary:** Implemented a service that handles automatic weekly and yearly notifications for faculty and students using SendGrid. It adds matching logic between students and projects/faculty based on shared research interests and sets up scheduled jobs to send emails accordingly. New database tables were added to store match relationships (not used for now, relationships are built on the spot when sending out emails, but if logging the matches is necessary they can be used). Added environment variable support for SendGrid credentials. 
- Added `project_student_matches` table to store matches between students and projects
- Added `student_faculty_matches` …
> Implemented Notification Service

- backend/src/main/java/COMP_49X_our_search/backend/gateway/GatewayController.java
- backend/src/main/java/COMP_49X_our_search/backend/gateway/dto/EmailNotificationTimeDTO.java
**New Feature**
**Summary:** 
Created the DTO for the EmailNotificationTime and wired that into the GatewayController in order to make the endpoint for the yearly notifications by email. 
1. Navigate to the Manage Variables page.
> Annual email endpoint

- README.md
- backend/src/main/java/COMP_49X_our_search/backend/gateway/GatewayController.java
- backend/src/main/java/COMP_49X_our_search/backend/security/OAuthSuccessHandler.java
- backend/src/main/java/COMP_49X_our_search/backend/security/SecurityConfig.java
- backend/src/main/java/COMP_49X_our_search/backend/security/SecurityConstants.java
- backend/src/test/java/COMP_49X_our_search/backend/BackendApplicationTests.java
- backend/src/test/java/COMP_49X_our_search/backend/authentication/AuthControllerIntegrationTest.java
- backend/src/test/java/COMP_49X_our_search/backend/database/DepartmentServiceIntegrationTest.java
- backend/src/test/java/COMP_49X_our_search/backend/database/FaqServiceIntegrationTest.java
- backend/src/test/java/COMP_49X_our_search/backend/database/MajorServiceIntegrationTest.java
- backend/src/test/java/COMP_49X_our_search/backend/gateway/GatewayControllerTest.java
- backend/src/test/java/COMP_49X_our_search/backend/security/OAuthSuccessHandlerTest.java
- backend/src/test/java/COMP_49X_our_search/backend/security/OAuthSuccessIntegrationTest.java
- backend/src/test/java/COMP_49X_our_search/backend/security/SecurityConfigTest.java
- backend/src/test/java/COMP_49X_our_search/backend/security/SecurityIntegrationTest.java
- compose.yaml
- frontend/Dockerfile
- frontend/nginx.conf
- frontend/src/App.js
- frontend/src/__tests__/admin/view/AdminEmails.test.js
- frontend/src/__tests__/navigation/TitleButton.test.js
- frontend/src/components/admin/AdminEmailNotification.js
- frontend/src/components/admin/WeeklyNotificationSelector.js
- frontend/src/components/navigation/TitleButton.js
- frontend/src/resources/constants.js
- frontend/src/resources/mockData.js
- nginx.conf
- start.sh
**Type of Change:** Bug Fix & Documentation
**Summary:** 
1. Made the domain name of the app configurable on startup. Before, our references to `FRONTEND_URL` and `BACKEND_URL` were hardcoded. Now, the user who starts the app specifies it (as a required field) when they run `./start.sh`. I named only one required field DOMAIN because the app is served with NGINX, making the only difference between the frontend url and backend url that the backend url has /api at the end. 
2. I updated the README to reflect the new changes.  
3. I also fixed two bugs relating to the /email-templates-time and /weekly-notifications that I ran into while I was running the app. The request bodies and endpoint names were inconsistent, leading to errors. 
1. cd  to root
2. run ./start.sh --google_id=<...> …
> Bug fixes & docs: notification bugs, configurable domain name, readme updates

- backend/src/main/java/COMP_49X_our_search/backend/gateway/GatewayController.java
- backend/src/main/java/COMP_49X_our_search/backend/notifications/SendGridService.java
- backend/src/main/java/COMP_49X_our_search/backend/project/ProjectCreator.java
- backend/src/main/java/COMP_49X_our_search/backend/security/RoleAuthorizationService.java
- backend/src/test/java/COMP_49X_our_search/backend/gateway/GatewayControllerTest.java
- backend/src/test/java/COMP_49X_our_search/backend/security/SecurityIntegrationTest.java
**Type of Change:** Bug fixes & New Feature
**Summary:** Fixed bug where environment variable was not named properly in the code. Fixed Project module logic to account for the new `created_at` field in the `Project` entity. Added annotation to endpoints to protect them with user roles.
- Added new class to verify user roles
N/A
> Fixed bugs & added endpoint protection

- README.md
- backend/.dockerignore
- backend/Dockerfile
- backend/build.gradle.kts
- compose.yaml
- frontend/Dockerfile
- mydb.sh
- nginx.conf
**Type of Change:** Refactoring
**Summary:**  
This PR updates infrastructure configuration to support SSL termination via Nginx and proper proxying to the backend service. The goal is to prepare the app for secure deployment in a production-like environment. Changes include:
- Modifying `nginx.conf` to enable HTTPS and reverse proxy logic
- Updating `docker-compose.yaml` to mount SSL certs and expose ports 80/443
- Adjusting backend Dockerfile and build.gradle.kts to target Java 21 for compatibility
- Pulling more efficient base images and reducing unnecessary file copying in Docker builds
- Minor clarifications added to the README
(I already pushed the new code to our image repositories)
1. From the Digital Ocean VM (ssh …
> Chore: Build Config Fixes and SSL Reverse Proxying

- frontend/src/__tests__/admin/view/AdminEmailNotification.test.js
- frontend/src/__tests__/navigation/SharedLayout.test.js
- frontend/src/__tests__/posts/PostsLayout.test.js
- frontend/src/components/FAQs.js
- frontend/src/components/admin/AdminEmailNotification.js
- frontend/src/components/posts/PostsLayout.js
**Summary:** Fixed some parts of the frontend to function in a more efficient and user friendly way. Now:
1. the posts load and only call the backend once (before I was handling the fetchPostings functions in a messy way)
2. the admin can edit the faq with larger text boxes
3. the admin cant edit email template time (feat discarded)
4. when faculty dont have any projects yet, a correct message displays. 
see above
none
none
none
1. login
2. see changes
> Frontend usability/bug fixes

- backend/src/main/java/COMP_49X_our_search/backend/notifications/EmailNotificationScheduler.java
- backend/src/main/java/COMP_49X_our_search/backend/notifications/SendGridService.java
- backend/src/main/resources/email-notifications.json
**Summary:** Implemented dynamic weekly notification templates for both students and faculty. Weekly emails now include personalized and student matches with rich HTML formatting, formatted using placeholder tags (`{interests}`, `{number_of_postings}`, `{new_postings}`, etc.) in the JSON templates.
- Refactored `EmailNotificationScheduler` to build HTML-based emails dynamically using helper methods.
- Added overloaded methods to `SendGridService` to support plain text, HTML, and multipart email sending.
WHATWHATWHATWHATWHATWHATWHAT
> Implemented dynamic weekly notification templates
