usd-cs/COMP-49X-24-25-our-search

- .gitignore
- backend/src/main/java/COMP_49X_our_search/backend/authentication/AuthCheckerInterface.java
- backend/src/main/java/COMP_49X_our_search/backend/authentication/AuthController.java
- backend/src/main/java/COMP_49X_our_search/backend/authentication/OAuthChecker.java
- backend/src/test/java/COMP_49X_our_search/backend/authentication/AuthControllerIntegrationTest.java
- backend/src/test/java/COMP_49X_our_search/backend/authentication/AuthControllerTest.java
- backend/src/test/java/COMP_49X_our_search/backend/authentication/OAuthCheckerTest.java
**Type of Change:**
New Feature
**Summary:**
Created an endpoint on the backend to retrieve the current user's authentication status. If the user is authenticated, the backend can respond saying that yes, they are. At this endpoint the backend can also tell the client what the user role is (student, faculty, admin). 
None
None
None
New OAuthChecker class. This service checks if a user is authenticated, retrieves the authenticated user's email, provide a default authentication response structure. This class implements an interface I created called AuthCheckerInterface. This is in case we switch to another auth provider.  Note that this is for oauth2 login but we could switch to CAS.
I created the endpoint with a controller, an interface for a service the endpoint can use to handle the …
> Check auth endpoint

- .github/workflows/gradle.yml
- backend/src/main/java/COMP_49X_our_search/backend/authentication/AuthController.java
- backend/src/main/java/COMP_49X_our_search/backend/security/EmailValidator.java
- backend/src/main/java/COMP_49X_our_search/backend/security/OAuthSuccessHandler.java
- backend/src/main/java/COMP_49X_our_search/backend/security/SecurityConfig.java
- backend/src/main/resources/application.properties
- backend/src/test/java/COMP_49X_our_search/backend/authentication/AuthControllerTest.java
- backend/src/test/java/COMP_49X_our_search/backend/gateway/GatewayControllerTest.java
- backend/src/test/java/COMP_49X_our_search/backend/security/EmailValidatorTest.java
- backend/src/test/java/COMP_49X_our_search/backend/security/OAuthSuccessHandlerTest.java
- backend/src/test/java/COMP_49X_our_search/backend/security/OAuthSuccessIntegrationTest.java
- backend/src/test/java/COMP_49X_our_search/backend/security/SecurityConfigTest.java
- backend/src/test/java/COMP_49X_our_search/backend/security/SecurityIntegrationTest.java
- backend/src/test/resources/application-test.properties
- frontend/src/__tests__/MainLayout.test.js
- frontend/src/components/MainLayout.js
- frontend/src/utils/fetchPostings.js
**Summary:** 
Implemented Google OAuth2 security for the backend application. Now all backend endpoints like /projects are not accessible unless you have logged in with Google and a USD email address. The backend is protected from anyone accessing the OUR's information now. 
No changes
No changes
- SecurityConfig is a class that extends one of Java Spring Security's classes to create a securityFilterChain which tells the backend what parts of the app to secure and how to secure them. 
- EmailValidator checks if the user's email is valid. 
- OAuthSuccessHandler overrides one of Java Spring Security's classes to handle what to do once the user has tried to log in with the oauth provider, in our case Google. 
1. navigating to http://localhost:8080 will prompt …
> Google oauth2

- backend/src/main/java/COMP_49X_our_search/backend/database/entities/User.java
- backend/src/main/java/COMP_49X_our_search/backend/database/enums/UserRole.java
- backend/src/main/java/COMP_49X_our_search/backend/database/repositories/UserRepository.java
- backend/src/main/java/COMP_49X_our_search/backend/database/services/UserService.java
- backend/src/test/java/COMP_49X_our_search/backend/database/UserServiceTest.java
**Summary:** Added User Hibernate Entity. Added UserService with get user by role functionality
Added "users" table that contains keys: `id` (primary), `email` (unique), and `userRole`.
Added new JpaRepository called UserRepository with `findByEmail()` method. Added new UserService with `getUserRoleByEmail()` method.
1) Make sure that the database has at least one user with set email and userRole in the "users" table.
2) Call the `getUserRoleByEmail()` method providing the existing email, and verify that the returned user role matches the expected result. Alternatively, call the method with a non-existent email and make sure that the method throws an …
> Added users table and get user role functionality

- frontend/src/__tests__/MainAccordion.test.js
- frontend/src/__tests__/MainLayout.test.js
- frontend/src/__tests__/MajorAccordion.test.js
- frontend/src/__tests__/PostList.test.js
- frontend/src/components/MainAccordion.js
- frontend/src/components/MainLayout.js
- frontend/src/components/MajorAccordion.js
- frontend/src/components/PostList.js
- frontend/src/resources/mockData.js
- frontend/src/utils/fetchPostings.js
Overview
Type of Change: New Feature
Summary:
This pull request updates the logic to ensure that the postings are rendered correctly based on the user role. Previously, the application displayed a generic student view regardless of user role. Now, when the user is a professor, the UI renders professor-specific information (first name, last name, class status, graduation year, majors, and email) instead of student opportunities. This change involved updating MainLayout.js, MainAccordion.js, MajorAccordion.js, and PostList.js, as well as adding/adjusting tests for both student and professor views.
UI/UX Implementation
The UI now conditionally displays posting details based on the user’s role:
Student view: Displays research opportunities, faculty names, and umbrella topics.
Professor view: …
> Check if user role is Professor and render the correct postings

- backend/src/main/java/COMP_49X_our_search/backend/security/UserRequestValidator.java
- backend/src/test/java/COMP_49X_our_search/backend/security/UserRequestValidatorTest.java
New Feature
**Summary:** Added helper class to determine whether a user can make a specific type of request. Only users with the `STUDENT` role should be able to make `/projects` requests, and only users with the `FACULTY` role should be able to make `/students` requests.
New class `UserRequestValidator` added, which contains the `canMakeRequest(String email, String requestType)` method that determines if the user with the given email is allowed to perform the given request.
1) Make sure that there is at least 1 valid user with role `STUDENT` in the database, and at least 1 valid user with the role `FACULTY`.
2) Write a helper class to call the `canMakeRequest` and test …
> Implemented helper class to validate /projects and /students requests

- backend/src/main/java/COMP_49X_our_search/backend/authentication/AuthController.java
- backend/src/main/java/COMP_49X_our_search/backend/database/entities/Department.java
- backend/src/main/java/COMP_49X_our_search/backend/database/entities/Discipline.java
- backend/src/main/java/COMP_49X_our_search/backend/database/entities/Major.java
- backend/src/main/java/COMP_49X_our_search/backend/fetcher/FetcherModuleController.java
- backend/src/main/java/COMP_49X_our_search/backend/gateway/GatewayController.java
- backend/src/main/java/COMP_49X_our_search/backend/gateway/dto/ProjectHierarchyDTO.java
- backend/src/main/java/COMP_49X_our_search/backend/gateway/util/ProjectHierarchyConverter.java
- backend/src/main/java/COMP_49X_our_search/backend/security/OAuthSuccessHandler.java
- backend/src/test/java/COMP_49X_our_search/backend/authentication/AuthControllerIntegrationTest.java
- backend/src/test/java/COMP_49X_our_search/backend/authentication/AuthControllerTest.java
- backend/src/test/java/COMP_49X_our_search/backend/database/MajorServiceTest.java
- backend/src/test/java/COMP_49X_our_search/backend/fetcher/ProjectFetcherTest.java
- backend/src/test/java/COMP_49X_our_search/backend/security/OAuthSuccessHandlerTest.java
- backend/src/test/resources/application-test.properties
- frontend/package.json
**Summary:** The backend endpoint to check if the user is authenticated or not no longer has hardcoded data to return. Now, it uses the userservice to check if the user has a profile or not and what their role is before sending a response. The oauthsuccessHandler also uses the userservice to determine what frontend url to redirect to after logging in. If they already have a profile, they are redirected to /posts, but if they are not, they are redirected to /ask-for-role.
I also fixed some linting errors by removing unused imports on all backend files.
Made use of the UserService class.
1. hit login
2. login
3. you will be redirect to /ask-for-role because you dont have a profile yet! (create profile is not yet integrated)
> Integrate backend userservice with security/authentication

- backend/src/main/java/COMP_49X_our_search/backend/security/EmailValidator.java
- backend/src/main/java/COMP_49X_our_search/backend/security/OAuthSuccessHandler.java
- backend/src/main/java/COMP_49X_our_search/backend/security/SecurityConfig.java
- backend/src/main/java/COMP_49X_our_search/backend/security/SecurityConstants.java
- backend/src/main/resources/application.properties
- backend/src/test/java/COMP_49X_our_search/backend/security/OAuthSuccessHandlerTest.java
- backend/src/test/java/COMP_49X_our_search/backend/security/OAuthSuccessIntegrationTest.java
- backend/src/test/java/COMP_49X_our_search/backend/security/SecurityConfigTest.java
- backend/src/test/java/COMP_49X_our_search/backend/security/SecurityIntegrationTest.java
**Type of Change:** New Feature/Bug Fix
**Summary:** 
Changed the logout mechanism to log the user out of their google accounts instead of just the application. This fixes a bug that has to do with OAuth2. Before the user could log out of our application, but Google would cache the previous login information, and bypass subsequent logins, no matter if they tried putting in a new email address. This would be a problem if multiple users with different USD emails logged in and out one after another. Google would cache the first login, preventing the second person from logging in as themselves. You would have to manually go to google.com and sign out. Now, logging out of the app signs you out of Google, removing that extra manual sign out step. 
n/a
n/a
n/a
n/a
1. login on the app from the …
> Logout of google entirely

- backend/src/main/java/COMP_49X_our_search/backend/database/entities/UmbrellaTopic.java
- backend/src/main/java/COMP_49X_our_search/backend/database/services/UmbrellaTopicService.java
- backend/src/main/java/COMP_49X_our_search/backend/gateway/GatewayController.java
- backend/src/main/java/COMP_49X_our_search/backend/gateway/dto/UmbrellaTopicDTO.java
- backend/src/test/java/COMP_49X_our_search/backend/database/UmbrellaTopicServiceTest.java
- backend/src/test/java/COMP_49X_our_search/backend/gateway/GatewayControllerTest.java
**Summary:** backend endpoint to return list of umbrella topics from the database at /umbrella-topics GET
No changes
Created UmbrellaTopicDTO with id and name
No changes
Created UmbrellaTopicService getAllUmbrellaTopics method
Updated GatewayController to use this service
1. login
2. go to backendurl/umbrella-topics
> Get umbrella topics

- backend/src/main/java/COMP_49X_our_search/backend/database/repositories/FacultyRepository.java
- backend/src/main/java/COMP_49X_our_search/backend/database/services/FacultyService.java
- backend/src/main/java/COMP_49X_our_search/backend/gateway/GatewayController.java
- backend/src/main/java/COMP_49X_our_search/backend/gateway/dto/EditFacultyRequestDTO.java
- backend/src/main/java/COMP_49X_our_search/backend/gateway/dto/FacultyDTO.java
- backend/src/main/java/COMP_49X_our_search/backend/gateway/util/ProjectHierarchyConverter.java
- backend/src/main/java/COMP_49X_our_search/backend/profile/FacultyProfileEditor.java
- backend/src/main/java/COMP_49X_our_search/backend/profile/ProfileModuleController.java
- backend/src/test/java/COMP_49X_our_search/backend/database/FacultyServiceTest.java
- backend/src/test/java/COMP_49X_our_search/backend/gateway/GatewayControllerTest.java
- backend/src/test/java/COMP_49X_our_search/backend/profile/FacultyProfileEditorTest.java
- backend/src/test/java/COMP_49X_our_search/backend/profile/ProfileModuleControllerTest.java
**Summary:** Added `PUT` endpoint `/api/facultyProfiles/current` to allow faculty profile editing.
- Added `FacultyProfileEditor` class in the `Profile` module that implements the `ProfileEditor` interface and is responsible for editing faculty profiles, which involves updating the existing faculty data in the `faculty` table and the appropriate relationship tables in the database.
- Added extra query methods in the hibernate service to support the needed operations.
1. Make sure the frontend app, backend app, and the mysql database are running, and that you are logged into the app with a valid user entry in the database.
2. Send …
> Implemented update faculty profile endpoint

- frontend/src/App.js
- frontend/src/__tests__/FacultyProfileView.test.js
- frontend/src/components/FacultyProfileView.js
- frontend/src/components/PostList.js
**Type of Change:** bug fix/new feat
**Summary:** The faculty profile view now shows the projects they are a part of. There is also a button to create new proejct. The form was missing this before. The projects are rendered as a post list like in the /posts page.
The view shows the projects now like in our ui prototype. https://www.figma.com/design/wVa9Sz9f2QpHebHeTVb0cI/Sprint-3?node-id=0-1&p=f&t=WX3BSILfGmmpxe1g-0 
No changes
No changes
No changes
1. login
2. assuming you have a faculty profile
3. click to view profile/projects
4. see them
> Faculty profile sees projects

- frontend/src/App.js
- frontend/src/__tests__/FacultyProfileView.test.js
- frontend/src/__tests__/StudentProfileView.test.js
- frontend/src/components/FacultyProfileView.js
- frontend/src/components/StudentProfileEdit.js
- frontend/src/components/StudentProfileView.js
**Type of Change:** Other/new feat
**Summary:** The student and faculty profile views now have delete buttons. Popups display to confirm deletion. Error messages display if needed. These buttons were missing from original user story implementation.
NOTE there are other commits on this branch because I merged main and another branch to avoid conflicts. 
Completion of UI prototype for sprint 3
none
none
none
1. login as student or faculty
2. go to view profile
3. see delete options
> Delete profile buttons on profile views

- backend/src/main/java/COMP_49X_our_search/backend/database/repositories/FacultyRepository.java
- backend/src/main/java/COMP_49X_our_search/backend/database/services/FacultyService.java
- backend/src/main/java/COMP_49X_our_search/backend/gateway/GatewayController.java
- backend/src/main/java/COMP_49X_our_search/backend/profile/FacultyProfileDeleter.java
- backend/src/main/java/COMP_49X_our_search/backend/profile/ProfileModuleController.java
- backend/src/main/java/COMP_49X_our_search/backend/profile/StudentProfileDeleter.java
- backend/src/test/java/COMP_49X_our_search/backend/database/FacultyServiceTest.java
- backend/src/test/java/COMP_49X_our_search/backend/gateway/GatewayControllerTest.java
- backend/src/test/java/COMP_49X_our_search/backend/profile/FacultyProfileDeleterTest.java
- backend/src/test/java/COMP_49X_our_search/backend/profile/ProfileModuleControllerTest.java
**Summary:** Added `DELETE` endpoint for `/api/facultyProfiles/current` to allow faculty profile and user deletion.
- Added `FacultyProfileDeleter` class in the `Profile` module that implements the `ProfileDeleter` interface and is responsible for deleting a faculty profile and user, which involves deleting the existing faculty data in the `users` table, and the `faculty` table and its respective relationship tables.
- Added extra query methods in the hibernate entity service to support the needed operations.
1. Make sure the frontend app, backend app, and the mysql database are running, and that you are logged into the app with a valid …
> Implemented delete faculty endpoint

- backend/src/main/java/COMP_49X_our_search/backend/gateway/GatewayController.java
- backend/src/main/java/COMP_49X_our_search/backend/gateway/dto/DisciplineDTO.java
- backend/src/main/java/COMP_49X_our_search/backend/gateway/dto/MajorDTO.java
- backend/src/test/java/COMP_49X_our_search/backend/gateway/GatewayControllerTest.java
**Summary:**
The GetMapping on the backend for disciplines used to return a list of disciplines by id and name. I changed GetMapping for disciplines to return the disciplines AND their majors, not just the id and name. This will be used in the frontend's ResearchOpportunityForm. The client asked that we change it so that it can render the major selection items grouped by discipline. 
No changes
No changes
No changes
No changes - I was able to reuse existing code to get majors by discipline id.
1. login
2. go to backendUrl/disciplines, will return list of disciplines and their majors are not null
> Get disciplines endpoint also returns majors

- backend/src/main/java/COMP_49X_our_search/backend/database/repositories/ProjectRepository.java
- backend/src/main/java/COMP_49X_our_search/backend/database/services/ProjectService.java
- backend/src/main/java/COMP_49X_our_search/backend/profile/FacultyProfileDeleter.java
- backend/src/test/java/COMP_49X_our_search/backend/profile/FacultyProfileDeleterTest.java
**Type of Change:** Bug Fix.
**Summary:** Fixed a bug where calling the `Profile` module to delete a faculty profile would attempt to delete the data from the `users` table, and the `faculty` table (and its respective relationship, i.e. `faculty_department`) but would not attempt to delete the project data, which used `faculty_id` as a foreign key referencing the `id` key in the `faculty` table.
**NOTE**: this could also be fixed by adding this to the `Faculty.java` hibernate class:
```
@OneToMany(mappedBy = "faculty", cascade = CascadeType.ALL, orphanRemoval = true)
private Set<Project> projects = new HashSet<>();
```
However, in the future we might need to support …
> Fixed faculty deletion not deleting projects

- backend/src/main/java/COMP_49X_our_search/backend/gateway/GatewayController.java
- backend/src/test/java/COMP_49X_our_search/backend/gateway/GatewayControllerTest.java
- frontend/src/App.js
- frontend/src/components/LandingPage.js
- frontend/src/resources/constants.js
**Summary:** Changed the endpoints to delete current student and faculty profiles to cause logout. Did this by changing a successful response to instead redirect to the logout URL on the backend, which triggers full logout process to avoid caching the user and removing all memory of authentication. I added messages to display on the frontend if the request fails.
Error messages on the landing page of the frontend
None
None
None
1. you wont see the error messages display on the frontend unless you intentionally don't run the backend (since right now the backend is working)
> updated delete current profile endpoints to cause logout

- backend/src/main/java/COMP_49X_our_search/backend/gateway/GatewayController.java
- backend/src/main/java/COMP_49X_our_search/backend/gateway/dto/EditStudentRequestDTO.java
- backend/src/main/java/COMP_49X_our_search/backend/security/LogoutHandler.java
- backend/src/main/java/COMP_49X_our_search/backend/security/LogoutService.java
- backend/src/main/java/COMP_49X_our_search/backend/security/OAuthSuccessHandler.java
- backend/src/test/java/COMP_49X_our_search/backend/gateway/GatewayControllerTest.java
- backend/src/test/java/COMP_49X_our_search/backend/security/LogoutServiceTest.java
- backend/src/test/java/COMP_49X_our_search/backend/security/OAuthSuccessHandlerTest.java
- frontend/src/App.js
- frontend/src/__tests__/profiles/StudentProfileEdit.test.js
- frontend/src/components/profiles/FacultyProfileView.js
- frontend/src/components/profiles/StudentProfileEdit.js
- frontend/src/components/profiles/StudentProfileView.js
- frontend/src/resources/mockData.js
**Summary:** There was an error with how I had implemented logging out previously due to CORS policies (the frontend, backend, and google URLs are configured in a way that only works in a certain way so that only certain origins can communicate in certain orders). Implemented a new LogoutService on the backend to use to effective log the user out when they delete their profile or try to sign in with the correct @sandiego email address. Fixed bugs on the frontend so that it is handled correctly when the user clicks logout, tries to sign in with the wrong email domain, or deletes their profile. 
No changes
GatewayController and OauthSuccessHandler now use Logout Service via dependency injection.
No changes
- New LogoutHandler interface requiring a method called …
> Logout / delete profile bug fix

- backend/src/main/java/COMP_49X_our_search/backend/database/repositories/FacultyRepository.java
- backend/src/main/java/COMP_49X_our_search/backend/database/services/FacultyService.java
- backend/src/main/java/COMP_49X_our_search/backend/fetcher/FacultyFetcher.java
- backend/src/main/java/COMP_49X_our_search/backend/fetcher/FetcherModuleController.java
- backend/src/main/java/COMP_49X_our_search/backend/gateway/GatewayController.java
- backend/src/main/java/COMP_49X_our_search/backend/gateway/dto/DepartmentDTO.java
- backend/src/main/java/COMP_49X_our_search/backend/gateway/dto/FacultyDTO.java
- backend/src/main/java/COMP_49X_our_search/backend/gateway/util/ProjectHierarchyConverter.java
- backend/src/main/java/COMP_49X_our_search/backend/util/ProtoConverter.java
- backend/src/main/proto/data/entities.proto
- backend/src/main/proto/fetcher/data_types.proto
- backend/src/main/proto/fetcher/fetcher_module.proto
- backend/src/test/java/COMP_49X_our_search/backend/database/FacultyServiceTest.java
- backend/src/test/java/COMP_49X_our_search/backend/fetcher/FacultyFetcherTest.java
- backend/src/test/java/COMP_49X_our_search/backend/fetcher/FetcherModuleControllerTest.java
- backend/src/test/java/COMP_49X_our_search/backend/fetcher/ProjectFetcherTest.java
- backend/src/test/java/COMP_49X_our_search/backend/gateway/GatewayControllerTest.java
- backend/src/test/java/COMP_49X_our_search/backend/profile/FacultyProfileRetrieverTest.java
- backend/src/test/java/COMP_49X_our_search/backend/util/ProtoConverterTest.java
**Summary:** Added `GET` `/all-faculty` endpoint to retrieve a list of faculty members grouped by department.
- Added `FacultyFetcher` in the `Fetcher` module that will be responsible for retrieving all faculty members and grouping them by department.
- Added extra query methods in the hibernate entity services to support the needed operations.
- Made changes to DTOs to support the expected response format.
1. Make sure the frontend app, backend app, and the mysql database are running and that there is valid data in the database, specifically valid faculty data, and valid project data.
2. Send `GET` request to endpoint …
> Implement retrieve grouped faculty endpoint

- backend/src/main/java/COMP_49X_our_search/backend/database/repositories/ProjectRepository.java
- backend/src/main/java/COMP_49X_our_search/backend/database/services/ProjectService.java
- backend/src/main/java/COMP_49X_our_search/backend/gateway/GatewayController.java
- backend/src/main/java/COMP_49X_our_search/backend/gateway/dto/DeleteRequestDTO.java
- backend/src/main/java/COMP_49X_our_search/backend/project/ProjectDeleter.java
- backend/src/main/java/COMP_49X_our_search/backend/project/ProjectModuleController.java
- backend/src/main/proto/project/project_module.proto
- backend/src/test/java/COMP_49X_our_search/backend/database/ProjectServiceTest.java
- backend/src/test/java/COMP_49X_our_search/backend/gateway/GatewayControllerTest.java
- backend/src/test/java/COMP_49X_our_search/backend/project/ProjectCreatorTest.java
- backend/src/test/java/COMP_49X_our_search/backend/project/ProjectDeleterTest.java
- backend/src/test/java/COMP_49X_our_search/backend/project/ProjectModuleControllerTest.java
**Summary:** Added `DELETE` mapping at `/project` endpoint to delete a specific project by its id.
- Added `ProjectDeleter` class in `Project` module that will be responsible for deleting a specific project by its id.
- Added extra query methods in the jpa entity services to support the needed operations.
- Renamed `DeleteStudentRequestDTO` to `DeleteRequestDTO`. All delete requests for admin users will have the same format, i.e. they will contain the `id` field, so having a single `DeleteRequestDTO` allows us to re-use code.
1. Make sure the frontend app, backend app, and the mysql database are running and that there is valid project data …
> Implement delete project endpoint

- frontend/src/components/MainAccordion.js
**Summary:** 
The frontend had a bug where if on student or faculty view it would show "1 opportunity" even though there were none to display. This is because the code did not filter out length of inactive postings when determining the number of posts. 
1. make sure database has projects and students in it
2. login as student or faculty
3. see accordion dropdowns with numbers of posts rendered correctly
Alternatively,
2. see all active and inactive postings with correct number displayed
> Fixed bug rendering number of posts available

- backend/src/main/java/COMP_49X_our_search/backend/database/repositories/DisciplineRepository.java
- backend/src/main/java/COMP_49X_our_search/backend/database/services/DisciplineService.java
- backend/src/main/java/COMP_49X_our_search/backend/database/services/MajorService.java
- backend/src/main/java/COMP_49X_our_search/backend/gateway/GatewayController.java
- backend/src/main/java/COMP_49X_our_search/backend/gateway/dto/EditMajorRequestDTO.java
- backend/src/test/java/COMP_49X_our_search/backend/database/DisciplineServiceTest.java
- backend/src/test/java/COMP_49X_our_search/backend/database/MajorServiceTest.java
- backend/src/test/java/COMP_49X_our_search/backend/gateway/GatewayControllerTest.java
**Summary:** Added `PUT` mapping at `/major` endpoint to edit a specific major by its id.
- Added extra query methods in the jpa services to support the needed operations.
1. Make sure the frontend app, backend app, and the mysql database are running and that there is valid major and discipline data in the database.
2. Send `PUT` request to endpoint `localhost:8080/major` icluding the appropriate data in the request body and verify that the response is as expected, and that the major was successfully edited.
> Implemented edit specific major endpoint

- frontend/src/components/admin/AdminFacultyEdit.js
**Type of Change:**  Bug Fix
**Summary:** On form for admin to edit faculty email, I changed the email field from `required` to `disabled` so they cannot edit the faculty's email address.
2. view a faculty profile
3. click edit
4. cannot edit the email
5. submit other edits to name and departments should work just fine
> disabled admin's ability to edit faculty email

- backend/src/main/java/COMP_49X_our_search/backend/authentication/AuthController.java
- backend/src/main/java/COMP_49X_our_search/backend/database/enums/UserRole.java
- backend/src/test/java/COMP_49X_our_search/backend/authentication/AuthControllerTest.java
**Type of Change:** New Feature / Refactoring
**Summary:** Added new `UserRole` enum: `ADMIN` to allow the backend to tell the frontend that a user is an admin.
- The `user_role` column in the `users` table now supports `ADMIN` to be a value.
1. Make sure you have valid admin user data in the `users` table 
2. Log in through the frontend
3. Make sure the backend returns true for isAdmin
> Adjust security settings to check for if user is admin

- backend/src/main/java/COMP_49X_our_search/backend/database/services/UmbrellaTopicService.java
- backend/src/main/java/COMP_49X_our_search/backend/gateway/GatewayController.java
- backend/src/test/java/COMP_49X_our_search/backend/database/UmbrellaTopicServiceTest.java
- backend/src/test/java/COMP_49X_our_search/backend/gateway/GatewayControllerTest.java
**Type of Change:** Implementation
**Summary:** Added `PUT` mapping at `/umbrellaTopic` endpoint a specific umbrellaTopic by its id.
- Added additional methods in the jpa umbrellaTopic services. 
-Make sure the frontend app, backend app, and the mysql database are running and that there is valid umbrella topic.
-Send 'PUT' request to the endpoint and verify the response is as expected, and that the umbrella topics were successfully changed.
> Implemented editUmbrellaTopic endpoint

- compose.yaml
**Summary:** `compose.yaml` now pulls from images in my docker hub's image repositories. This is so that we can prebuild the images on our local machines before pushing to our Digital Ocean droplets. The droplets did not have enough RAM to build the images, so our solution to making deployment work is to prebuild the images so that `docker compose up` only has to pull them. 
1. in the root directory of this project, run `docker compose up`. It should pull the images from my repositories and build the project in a matter of seconds. The built images are the latest as of today, 3/27/25 at 9pm.
> Modified compose.yaml to pull latest prebuilt images

- backend/src/main/java/COMP_49X_our_search/backend/database/entities/Discipline.java
- backend/src/main/java/COMP_49X_our_search/backend/database/entities/Student.java
- backend/src/main/java/COMP_49X_our_search/backend/database/services/DisciplineService.java
- backend/src/main/java/COMP_49X_our_search/backend/gateway/GatewayController.java
- backend/src/test/java/COMP_49X_our_search/backend/database/DisciplineServiceTest.java
- backend/src/test/java/COMP_49X_our_search/backend/gateway/GatewayControllerTest.java
**Summary:** Added `DELETE` mapping at `/discipline` endpoint to delete a specific discipline by its id.
- Added extra query methods in the jpa services to support the needed operations.
1. Make sure the frontend app, the backend app, and the mysql database are running and that there is valid discipline and, though not required, major data in the database.
2. Send `DELETE` request to endpoint `https://localhost:8080/discipline` including the appropriate data in the request body and verify that the response is as expected, and that the discipline was successfully deleted.
> Implemented delete specific discipline endpoint

- backend/src/main/java/COMP_49X_our_search/backend/database/services/DepartmentService.java
- backend/src/main/java/COMP_49X_our_search/backend/gateway/GatewayController.java
- backend/src/test/java/COMP_49X_our_search/backend/database/DepartmentServiceTest.java
- backend/src/test/java/COMP_49X_our_search/backend/gateway/GatewayControllerTest.java
**Summary:** Added `DELETE` mapping at `/department` endpoint to delete a specific department by its id.
- Added additional method in the jpa DepartmentService class to support the needed operations. 
1. Make sure the frontend app, the backend app, and the mysql database are running and that there is valid department data in the database.
2. Send `DELETE` request to endpoint `https://localhost:8080/department` including the id of the department in the request body and verify that the response is as expected, and that the department was successfully deleted.
> Implemented delete specific department endpoint

- backend/src/main/java/COMP_49X_our_search/backend/database/services/DisciplineService.java
- backend/src/main/java/COMP_49X_our_search/backend/gateway/GatewayController.java
- backend/src/test/java/COMP_49X_our_search/backend/database/DisciplineServiceTest.java
- backend/src/test/java/COMP_49X_our_search/backend/gateway/GatewayControllerTest.java
**Type of Change:** Implementation
**Summary:** Added a PUT mapping at /discipline to update a specific Discipline by its ID.
Added service methods for retrieving and saving Discipline entities in DisciplineService.
Ensure the system is running (frontend, backend, DB).
Confirm there’s an existing Discipline in the DB.
Send a PUT request with the Discipline ID and new name.
Check the response and database to confirm the name is updated.
> Implemented endpoint to edit Discipline

- backend/src/main/java/COMP_49X_our_search/backend/database/services/UmbrellaTopicService.java
- backend/src/main/java/COMP_49X_our_search/backend/gateway/GatewayController.java
- backend/src/test/java/COMP_49X_our_search/backend/database/UmbrellaTopicServiceTest.java
- backend/src/test/java/COMP_49X_our_search/backend/gateway/GatewayControllerTest.java
**Type of Change:** Implementation
**Summary:** Added a DELETE endpoint at /umbrella-topic to remove a specific umbrella topic by its ID.
Added a delete method in the umbrella topic service and integrated it into the gateway controller.
-Ensure the backend, frontend, and database are running.
-Verify that an umbrella topic exists in the database.
-Send a DELETE request to /umbrella-topic with the umbrella topic's ID in the payload.
-Confirm that a 200 OK response is returned and the umbrella topic is removed from the database.
> Implemented deleteSpecificUmbrella

- frontend/src/__tests__/posts/PostDialog.test.js
- frontend/src/components/posts/PostDialog.js
**Summary:** I had initially forgotten to only render the "edit profile/project" and "delete profile/project" buttons for only faculty. Now that is fixed.
https://www.figma.com/design/Ek8pc7TK5PKx4eI3i4C78G/Sprint-4?node-id=0-1&p=f&t=QlPDUOcKwqZO137V-0
1. login as student or faculty, view posts, no edit or delete buttons
2. login as faculty, view posts, see edit and delete buttons
> Bug fix: students and faculty to not see options to edit and delete posts

- backend/src/main/java/COMP_49X_our_search/backend/gateway/GatewayController.java
- backend/src/test/java/COMP_49X_our_search/backend/gateway/GatewayControllerTest.java
**Type of Change:** Added a new POST /discipline endpoint to create a discipline record. The endpoint validates the discipline name and returns the created discipline.
**Summary:** Added a DELETE endpoint at /umbrella-topic to remove a specific umbrella topic by its ID.
Added a delete method in the umbrella topic service and integrated it into the gateway controller.
Ensure the backend, frontend, and database are running.
Verify that an umbrella topic exists in the database.
Send a DELETE request to /umbrella-topic with the umbrella topic's ID in the payload.
> Implemented Endpoint to create new discipline

- backend/src/main/java/COMP_49X_our_search/backend/database/services/MajorService.java
- backend/src/main/java/COMP_49X_our_search/backend/gateway/GatewayController.java
- backend/src/test/java/COMP_49X_our_search/backend/database/MajorServiceTest.java
- backend/src/test/java/COMP_49X_our_search/backend/gateway/GatewayControllerTest.java
**Summary:** Added `DELETE` mapping at `/major` endpoint to delete a specific major by its id.
- Added additional method in jpa service to support needed operations.
1. Make sure the frontend app, the backend app, and the musql database are running and that there is valid major data in the database.
2. Send `DELETE` request to endpoint `https://localhost:8080/major` including the id of the major in the request body and verify that the response is as expected, and that either the major was deleted successfully or that an error was returned if the major was associated with projects or students.
> Implemented delete major endpoint

- frontend/src/__tests__/admin/add/handleAddDepartment.test.js
- frontend/src/__tests__/admin/add/handleAddDiscipline.test.js
- frontend/src/__tests__/admin/add/handleAddMajor.test.js
- frontend/src/__tests__/admin/add/handleAddPeriod.test.js
- frontend/src/__tests__/admin/add/handleAddUmbrella.test.js
- frontend/src/__tests__/admin/delete/handleDeleteDepartment.test.js
- frontend/src/__tests__/admin/delete/handleDeleteDiscipline.test.js
- frontend/src/__tests__/admin/delete/handleDeleteMajor.test.js
- frontend/src/__tests__/admin/delete/handleDeletePeriod.test.js
- frontend/src/__tests__/admin/delete/handleDeleteUmbrella.test.js
- frontend/src/__tests__/admin/edit/handleSaveDepartment.test.js
- frontend/src/__tests__/admin/edit/handleSaveDiscipline.test.js
- frontend/src/__tests__/admin/edit/handleSaveMajor.test.js
- frontend/src/__tests__/admin/edit/handleSavePeriod.test.js
- frontend/src/__tests__/admin/edit/handleSaveUmbrella.test.js
- frontend/src/utils/adminFetching.js
**Type of Change:** bug fix
**Summary:** admin functions to add, edit, and delete app variables did not have credentials: 'include' in fetch calls to backend. this is needed for authentication, otherwise the requests will not work. forgot to add this before
> frontend bug: admin functions did not include credentials

- backend/src/main/java/COMP_49X_our_search/backend/database/repositories/MajorRepository.java
- backend/src/main/java/COMP_49X_our_search/backend/database/services/MajorService.java
- backend/src/main/java/COMP_49X_our_search/backend/gateway/GatewayController.java
- backend/src/test/java/COMP_49X_our_search/backend/database/MajorServiceTest.java
- backend/src/test/java/COMP_49X_our_search/backend/gateway/GatewayControllerTest.java
- frontend/src/__tests__/admin/add/handleAddMajor.test.js
- frontend/src/__tests__/admin/delete/handleDeleteDiscipline.test.js
- frontend/src/__tests__/admin/edit/handleSaveDepartment.test.js
- frontend/src/__tests__/admin/edit/handleSaveDiscipline.test.js
- frontend/src/__tests__/admin/edit/handleSaveMajor.test.js
- frontend/src/__tests__/admin/edit/handleSavePeriod.test.js
- frontend/src/__tests__/admin/edit/handleSaveUmbrella.test.js
- frontend/src/__tests__/admin/view/ManageVariables.test.js
- frontend/src/components/admin/AdminEmailNotification.js
- frontend/src/components/admin/ManageVariables.js
- frontend/src/components/admin/RenderAdminVariables.js
- frontend/src/resources/mockData.js
- frontend/src/utils/adminFetching.js
**Summary:** The client requested changes to the admin view for sprint 5. They want to be able to edit, add, and delete disciplines and majors separately. This means that the program logic had to change for how those functions were handled. 
* My solution was to have the `GET /disciplines` endpoint also return a discipline value with id = -1, name '' , and majors being a list of majors without a discipline. This could fit with the existing way that disciplines and majors were rendered on the frontend. 
* Then on the frontend I updated the `handleDeleteDisciplines` function to call the backend again after successful deletion to update the disciplines/majors rendered on the screen, in case any associations are updated.
* Had to update `handleSaveMajor` and …
> Admin feat to delete disciplines with no majors; control majors with no disciplines

- frontend/src/__tests__/posts/PostDialog.test.js
- frontend/src/__tests__/posts/PostList.test.js
- frontend/src/__tests__/projects/ProjectEdit.test.js
- frontend/src/components/posts/PostDialog.js
- frontend/src/components/posts/PostList.js
- frontend/src/components/profiles/FacultyProfileView.js
- frontend/src/components/projects/ProjectEdit.js
**Summary:** Updated the frontend so that faculty can now edit their own projects. Reused `ProjectEdit.js` that allows admins to also edit projects, however the component is rendered from the `PostDialog` component rather than from a route. While admins edit from /project/id, faculty must be able to edit from the same page as their profile, /view-professor-profile, to prevent faculty from being able to go to any /project/id and edit any project. Faculty. Props like showingMyFacultyProject, isFaculty, etc make it so faculty can’t edit any project; only their own.
https://www.figma.com/design/DhiOgiITPexVdSPS3W333C/Sprint-5?node-id=0-1&p=f&t=U2QYIt5bKObo3a7t-0
New props and small logic changes to render proper data for faculty in:
PostDialog
PostList …
> Faculty can edit their own projects

- backend/src/main/java/COMP_49X_our_search/backend/database/entities/Faq.java
- backend/src/main/java/COMP_49X_our_search/backend/database/enums/FaqType.java
- backend/src/main/java/COMP_49X_our_search/backend/database/repositories/FaqRepository.java
- backend/src/main/java/COMP_49X_our_search/backend/database/services/FaqService.java
- backend/src/main/java/COMP_49X_our_search/backend/gateway/GatewayController.java
- backend/src/main/java/COMP_49X_our_search/backend/gateway/dto/FaqDTO.java
- backend/src/test/java/COMP_49X_our_search/backend/database/FaqServiceTest.java
- backend/src/test/java/COMP_49X_our_search/backend/gateway/GatewayControllerTest.java
**Summary:** Added `GET` mappings at endpoints `all-student-faqs`, `all-faculty-faqs`, and `all-admin-faqs` to retrieve all FAQs by type.
- Added new JPA Entity called `Faq` that will correspond to the `faqs` table with columns `id`, `question`, `answer`, and `type`.
- Added JPA repository and service for the new `Faq` entity.
- Added new enum `FaqType` with possible values: `STUDENT`, `FACULTY`, `ADMIN`.
1. Make sure the frontend app, the backend app, and the mysql database are running and that there is valid faq data in the database.
2. Send `GET` request to endpoint `http://localhost:8080/all-student-faqs`, `http://localhost:8080/all-faculty-faqs`, and …
> Implemented retrieve FAQs endpoint

- frontend/src/__tests__/MainAccordion.test.js
- frontend/src/__tests__/admin/view/AdminEmailNotification.test.js
- frontend/src/__tests__/admin/view/renderMajors.test.js
- frontend/src/__tests__/posts/PostList.test.js
- frontend/src/components/MainAccordion.js
- frontend/src/components/admin/AdminEmailNotification.js
- frontend/src/components/admin/ManageVariables.js
- frontend/src/components/admin/RenderAdminVariables.js
- frontend/src/components/navigation/SharedLayout.js
- frontend/src/components/posts/PostDialog.js
- frontend/src/components/posts/PostList.js
- frontend/src/components/projects/ProjectEdit.js
- frontend/src/resources/constants.js
- frontend/src/resources/mockData.js
**Type of Change:** Bug Fixes
**Summary:** 
- faculty can now click edit project to see their project
- faculty closing edit project view now works
- bottom nav bar has padding to not be in the way
- disciplines with no majors show up with "no research fields available"
- on admin page, majors with no discipline show "Other" as preselected "discipline" but sending an edit or add request without any discipline selected still works
- email notification page now requests from correct endpoint
Nothing changed about original plan; this PR corrects errors.
> Fixed bugs editing projects, editing majors, and rendering majors/disciplines for admin on frontend

- frontend/src/components/admin/ManageVariables.js
- frontend/src/components/admin/RenderAdminVariables.js
**Type of Change:** Refactor
**Summary:** Decided to filter for the "Other" discipline on the frontend by filtering for `name` field rather than 'id` field. This is because we have decided to create a whole new discipline in the db called "Other". Any request to edit disciplines won't be able to change the name of it, so it's name will always be unique and able to find. Also, we can't set the id to -1 so we can't check based on the id.
> Changed frontend to look for "Other" discipline by name instead of id

- backend/src/main/java/COMP_49X_our_search/backend/database/entities/Discipline.java
- backend/src/main/java/COMP_49X_our_search/backend/database/entities/Major.java
- backend/src/main/java/COMP_49X_our_search/backend/database/services/DisciplineService.java
- backend/src/main/java/COMP_49X_our_search/backend/database/services/MajorService.java
- backend/src/main/java/COMP_49X_our_search/backend/gateway/GatewayController.java
- backend/src/main/java/COMP_49X_our_search/backend/util/Constants.java
- backend/src/main/java/COMP_49X_our_search/backend/util/exceptions/ForbiddenDisciplineActionException.java
- backend/src/main/java/COMP_49X_our_search/backend/util/exceptions/ForbiddenMajorActionException.java
- backend/src/test/java/COMP_49X_our_search/backend/database/DisciplineServiceTest.java
- backend/src/test/java/COMP_49X_our_search/backend/database/MajorServiceTest.java
- backend/src/test/java/COMP_49X_our_search/backend/gateway/GatewayControllerTest.java
**Type of Change:** New Feature / Refactoring.
**Summary:** Logic changes for the special cases of the `Discipline` and `Major` JPA entities, specifically for the `"Other"` discipline and the `"Undeclared"` major. These changes make sure that:
- The special cases are created automatically if they don't exist.
- Cannot be manually created, edited, or deleted by users.
- Updated `"Discipline"` and `"Major"` entities to make the `name` field unique.
- Added auto-initialization of special entries "Other" for disciplines and "Undeclared" for majors added in `@PostConstruct`.
- Updated `DisciplineService` and `MajorService` with new auto-initialization methods: `initializeSpecialDisciplines()` …
> Added support for "Other" discipline and "Undeclared" major

- backend/src/main/java/COMP_49X_our_search/backend/database/services/FaqService.java
- backend/src/main/java/COMP_49X_our_search/backend/gateway/GatewayController.java
- backend/src/main/java/COMP_49X_our_search/backend/gateway/dto/FaqRequestDTO.java
- backend/src/test/java/COMP_49X_our_search/backend/database/FaqServiceTest.java
- backend/src/test/java/COMP_49X_our_search/backend/gateway/GatewayControllerTest.java
**Summary:** Added `POST` mapping at endpoint `/faq` to support creating new FAQs.
- Added new `FaqRequestDTO` that will be used for `POST`/`PUT`/`DELETE` requests. Some fields in this DTO will be ignored depending on the request, e.g. in this PR since we're creating a new Faq, we'll ignore the `id` field.
- Added additional method in the Jpa service to support the needed operations.
1. Make sure the frontend app, the backend app, and the mysql database are running
2. Send `POST` request to endpoint `http://localhost:8080/faq` with valid data in the request body, and verify that the responses are as expected and includes the data of the …
> Implement create FAQ endpoint

- frontend/src/App.js
- frontend/src/__tests__/App.test.js
**Summary:** The login button now sends the user to /posts if they have already logged in. Before, it would try to go back to login, but there would be an error if the user has already logged in on the backend. This bypasses trying to re-login on the backend. The user must logout before logging in again.
1. login
2. go back to the login/landing page
3. click login again
4. will go to /posts instead of "Whitelabel error page"
> bug fix: login button navigates to posts page if the user is already logged in

- frontend/src/__tests__/admin/add/handleAddDiscipline.test.js
- frontend/src/__tests__/admin/add/handleAddMajor.test.js
- frontend/src/__tests__/admin/delete/handleDeleteDiscipline.test.js
- frontend/src/__tests__/admin/delete/handleDeleteMajor.test.js
- frontend/src/__tests__/admin/edit/handleSaveDiscipline.test.js
- frontend/src/__tests__/admin/edit/handleSaveMajor.test.js
- frontend/src/utils/adminFetching.js
**Summary:** The frontend now renders an error message if the backend responds with 403 for trying to edit, add, or delete the "Undeclared" major or "Other" discipline. These are permanent and should not be manipulated by the admin. Now the frontend shows a message so they know why there was an error.
New error message wording. Such as "'Undeclared' is permanent and cannot be deleted." We did not account for these messages before.
No changes
No changes
No changes
2. go to manage-app-variables page by clicking button to go there
3. try to edit the 'undeclared' major. It won't work and a message will display.
4. try to add another 'undeclared' major. It won't work and a message will display. 
5. same for disciplines with 'other'
> display message if admin tries to edit "Undeclared" or "Other"

- backend/src/main/java/COMP_49X_our_search/backend/database/services/FaqService.java
- backend/src/main/java/COMP_49X_our_search/backend/gateway/GatewayController.java
- backend/src/test/java/COMP_49X_our_search/backend/database/FaqServiceTest.java
- backend/src/test/java/COMP_49X_our_search/backend/gateway/GatewayControllerTest.java
**Type of Change:** New Feature.
**Summary:** Added `PUT` mapping at endpoint `/faq` to support editing existing FAQs.
- Added additional method (`getFaqById(int id)`) in the Jpa service to support the needed operations.
1. Make sure the frontend app, the backend app, and the mysql database are running, and that there is valid faq data in the database.
2. Send `PUT` request to endpoint `http://localhost:8080/faq` with valid data in the request body, and verify that the response is as expected and that the FAQ was successfully edited.
> Implemented edit FAQ endpoint

- frontend/src/__tests__/posts/PostDialog.test.js
- frontend/src/components/posts/PostDialog.js
- frontend/src/components/profiles/FacultyProfileView.js
- frontend/src/components/projects/ProjectEdit.js
- frontend/src/resources/constants.js
**Summary:** Edit project page was still showing up even after the faculty had finished editing it and closed the window. Fixed that bug so now after closing the window the edit project page is not visible until you click "edit project" again.
1. login as faculty
2. click view my profile
3. click on a project
4. click edit project
5. close window
6. click on project again -> no longer editing the project
> Bug fix: faculty closing edit project window

- frontend/src/__tests__/navigation/SharedLayout.test.js
- frontend/src/components/navigation/SharedLayout.js
**Summary:** Client said they don't need the extra icons for admin navigation on the top bar. Can navigate there with other buttons that already exist.
2. see that there are no icon buttons on top right
> Removed admin nav icons

- frontend/src/__tests__/filtering/SearchBar.test.js
- frontend/src/components/filtering/SearchBar.js
**New Feature**
**Summary:** 
In this PR, the logic for the SearchBar component was improved to let users type a query that then pushes it into the URL’s search parameter without any need for reloading the page and whenever they either hit Enter or the search icon.
Start the app 
Navigate to a list page, type “foo” into the search bar and press Enter or the Search icon. Verify the URL changes to ?search=foo
Clear the search box, press Enter again.
> Implementing SearchBar Logic

- backend/src/main/java/COMP_49X_our_search/backend/gateway/util/ProjectHierarchyConverter.java
- backend/src/test/java/COMP_49X_our_search/backend/gateway/ProjectHierarchyConverterTest.java
**Summary:** Fixed bug where disciplines with no majors would throw an error when calling the `/all-projects` or `/all-students` endpoint.
1) Make sure the frontend app, backend app, and mysql database are running, and that there is valid data in the database, specifically majors and disciplines, and that at least 1 discipline is 'empty', i.e. no major is associated to it.
2) Send `GET` request at endpoints `/all-projects' or `/all-students` and make sure that the response is as expected and without errors.
> Fixed discipline with no majors bug

- backend/src/main/java/COMP_49X_our_search/backend/database/services/DisciplineService.java
- backend/src/test/java/COMP_49X_our_search/backend/database/DisciplineServiceTest.java
**Summary:** Fixed bug where if we delete a discipline and there is a major that belonged to only that discipline, the major would stay unassociated, instead of being reassigned to the "Other" discipline.
1. Make sure you have valid major and discipline data in the database, and at least one major that belongs to only 1 discipline. 
2. Delete the discipline and verify that the major was moved to "Other"
> Fixed deleting discipline bug

- frontend/src/components/filtering/Sidebar.js
**Summary:**  Fixed `sidebar.js` component so that:
- changing posts view from projects to students or vice versa resets the filters. There are different filters on projects vs students, so the selected filters should reset. 
- reloading the page with no URL params resets the filters
- reloading the page with URL params applies those filters
- all filter data is always loaded (before research periods was not showing up)
no changes
no changes
no changes
no changes
1. login as faculty or admin
2. all of these will work:
1. add filters
2. reset filters
3. reload page
4. switching between tabs
> bug fix: reseting filters; rendering filters

- backend/src/main/java/COMP_49X_our_search/backend/database/services/UserService.java
- backend/src/test/java/COMP_49X_our_search/backend/database/UserServiceTest.java
- compose.yaml
- start.sh
**Summary:** Added support for creating an admin user when initializing the app for the first time.
- Added `@PostConstruct` method in the `UserService` to create an admin user upon initialization.
- Either:
- Set environment variable `ADMIN_EMAIL` in `compose.yaml` and run command `./start.sh`, or
- Run command `./start.sh --new_admin=<admin_email>`.
- Verify that the admin user was created
> Add support for creating an admin user via start script and environment variable

- compose.yaml
- start.sh
**Summary:** Made the Google credentials configurable **and required** whenever the app starts via the start script. This way, users can configure their own Google client. 
1. Run command `./start.sh --google_id=<xyz> --google_secret=<xyz>`.
2. Click login. Verify that it worked if logging in redirects you to Google.
> Support for configuring Google credentials via start script

- frontend/src/__tests__/filtering/SearchBar.test.js
- frontend/src/components/filtering/SearchBar.js
- frontend/src/components/filtering/Sidebar.js
- frontend/src/components/posts/PostsLayout.js
**Summary:** Made it so hitting Apply, enter on the search bar, or the search icon on the search bar will set all filters and search. Hitting reset will reset the search bar and all the filters. This is for making filtering consistent.
none
none
none
none
1. login
2. enter search query. click apply or enter or the search icon. will send the search. 
3. enter search query, then click filters. click apply or enter or search icon. will send the search and the filters.
4. enter filters, then search query. click apply or enter or search icon. will send the search and the filters.
5. enter filters. apply. will send filters. enter search. apply. will send search with previous filters. 
6. enter search. apply. will send search. enter filters. apply. will send …
> feat: apply button sends search now

- backend/src/main/java/COMP_49X_our_search/backend/database/repositories/UserRepository.java
- backend/src/main/java/COMP_49X_our_search/backend/database/services/UserService.java
- backend/src/main/java/COMP_49X_our_search/backend/gateway/GatewayController.java
- backend/src/main/java/COMP_49X_our_search/backend/gateway/dto/AdminEmailDTO.java
- frontend/src/__tests__/admin/delete/handleDeleteAdminEmail.test.js
- frontend/src/resources/mockData.js
- frontend/src/utils/adminFetching.js
- frontend/src/utils/fetchDepartments.js
- frontend/src/utils/fetchDisciplines.js
- frontend/src/utils/fetchMajors.js
- frontend/src/utils/fetchResearchPeriods.js
- frontend/src/utils/fetchUmbrellaTopics.js
- frontend/src/utils/getDataFrom.js
**Summary:** Deleting an email was not working for admins. It was returning 404 because the backend endpoint was misconfigured in the backend.
To fix, I fixed the backend so that the ID of the admin users are returned to the frontend and then used to delete the admin from the database. I also added a check in the backend endpoint to make sure the user can't delete the email if it's the one they are currently logged in as. This prevents the admin from accidentally deleting the only admin email that exists, and accidentally logging themself out.
The frontend now displays an error message of they try to delete the email they are currently logged in with.
AdminEmailDTO now includes the id.
userService now handles deleteUserById.
No changes
2. go …
> Bug: admin delete email
